package org.you.oops.order.domain.userorder.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.you.oops.order.domain.userorder.repository.po.BbcOrderPaymentPO;
import org.you.oops.order.domain.userorder.repository.po.BbcOrderPaymentExample;

public interface BbcOrderPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    long countByExample(BbcOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int deleteByExample(BbcOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String forderPaymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int insert(BbcOrderPaymentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int insertSelective(BbcOrderPaymentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    List<BbcOrderPaymentPO> selectByExampleWithBLOBs(BbcOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    List<BbcOrderPaymentPO> selectByExample(BbcOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    BbcOrderPaymentPO selectByPrimaryKey(String forderPaymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") BbcOrderPaymentPO record, @Param("example") BbcOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int updateByExampleWithBLOBs(@Param("record") BbcOrderPaymentPO record, @Param("example") BbcOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int updateByExample(@Param("record") BbcOrderPaymentPO record, @Param("example") BbcOrderPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(BbcOrderPaymentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int updateByPrimaryKeyWithBLOBs(BbcOrderPaymentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order_payment
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    int updateByPrimaryKey(BbcOrderPaymentPO record);
}