package org.you.oops.order.domain.userorder.repository.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BbcOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public BbcOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andForderIdIsNull() {
            addCriterion("forder_id is null");
            return (Criteria) this;
        }

        public Criteria andForderIdIsNotNull() {
            addCriterion("forder_id is not null");
            return (Criteria) this;
        }

        public Criteria andForderIdEqualTo(String value) {
            addCriterion("forder_id =", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdNotEqualTo(String value) {
            addCriterion("forder_id <>", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdGreaterThan(String value) {
            addCriterion("forder_id >", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdGreaterThanOrEqualTo(String value) {
            addCriterion("forder_id >=", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdLessThan(String value) {
            addCriterion("forder_id <", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdLessThanOrEqualTo(String value) {
            addCriterion("forder_id <=", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdLike(String value) {
            addCriterion("forder_id like", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdNotLike(String value) {
            addCriterion("forder_id not like", value, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdIn(List<String> values) {
            addCriterion("forder_id in", values, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdNotIn(List<String> values) {
            addCriterion("forder_id not in", values, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdBetween(String value1, String value2) {
            addCriterion("forder_id between", value1, value2, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderIdNotBetween(String value1, String value2) {
            addCriterion("forder_id not between", value1, value2, "forderId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdIsNull() {
            addCriterion("forder_payment_id is null");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdIsNotNull() {
            addCriterion("forder_payment_id is not null");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdEqualTo(String value) {
            addCriterion("forder_payment_id =", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdNotEqualTo(String value) {
            addCriterion("forder_payment_id <>", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdGreaterThan(String value) {
            addCriterion("forder_payment_id >", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdGreaterThanOrEqualTo(String value) {
            addCriterion("forder_payment_id >=", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdLessThan(String value) {
            addCriterion("forder_payment_id <", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdLessThanOrEqualTo(String value) {
            addCriterion("forder_payment_id <=", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdLike(String value) {
            addCriterion("forder_payment_id like", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdNotLike(String value) {
            addCriterion("forder_payment_id not like", value, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdIn(List<String> values) {
            addCriterion("forder_payment_id in", values, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdNotIn(List<String> values) {
            addCriterion("forder_payment_id not in", values, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdBetween(String value1, String value2) {
            addCriterion("forder_payment_id between", value1, value2, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderPaymentIdNotBetween(String value1, String value2) {
            addCriterion("forder_payment_id not between", value1, value2, "forderPaymentId");
            return (Criteria) this;
        }

        public Criteria andForderTypeIsNull() {
            addCriterion("forder_type is null");
            return (Criteria) this;
        }

        public Criteria andForderTypeIsNotNull() {
            addCriterion("forder_type is not null");
            return (Criteria) this;
        }

        public Criteria andForderTypeEqualTo(Integer value) {
            addCriterion("forder_type =", value, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeNotEqualTo(Integer value) {
            addCriterion("forder_type <>", value, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeGreaterThan(Integer value) {
            addCriterion("forder_type >", value, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("forder_type >=", value, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeLessThan(Integer value) {
            addCriterion("forder_type <", value, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeLessThanOrEqualTo(Integer value) {
            addCriterion("forder_type <=", value, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeIn(List<Integer> values) {
            addCriterion("forder_type in", values, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeNotIn(List<Integer> values) {
            addCriterion("forder_type not in", values, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeBetween(Integer value1, Integer value2) {
            addCriterion("forder_type between", value1, value2, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("forder_type not between", value1, value2, "forderType");
            return (Criteria) this;
        }

        public Criteria andForderStatusIsNull() {
            addCriterion("forder_status is null");
            return (Criteria) this;
        }

        public Criteria andForderStatusIsNotNull() {
            addCriterion("forder_status is not null");
            return (Criteria) this;
        }

        public Criteria andForderStatusEqualTo(Integer value) {
            addCriterion("forder_status =", value, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusNotEqualTo(Integer value) {
            addCriterion("forder_status <>", value, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusGreaterThan(Integer value) {
            addCriterion("forder_status >", value, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("forder_status >=", value, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusLessThan(Integer value) {
            addCriterion("forder_status <", value, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("forder_status <=", value, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusIn(List<Integer> values) {
            addCriterion("forder_status in", values, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusNotIn(List<Integer> values) {
            addCriterion("forder_status not in", values, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusBetween(Integer value1, Integer value2) {
            addCriterion("forder_status between", value1, value2, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andForderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("forder_status not between", value1, value2, "forderStatus");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeIsNull() {
            addCriterion("fcancel_type is null");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeIsNotNull() {
            addCriterion("fcancel_type is not null");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeEqualTo(Integer value) {
            addCriterion("fcancel_type =", value, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeNotEqualTo(Integer value) {
            addCriterion("fcancel_type <>", value, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeGreaterThan(Integer value) {
            addCriterion("fcancel_type >", value, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fcancel_type >=", value, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeLessThan(Integer value) {
            addCriterion("fcancel_type <", value, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("fcancel_type <=", value, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeIn(List<Integer> values) {
            addCriterion("fcancel_type in", values, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeNotIn(List<Integer> values) {
            addCriterion("fcancel_type not in", values, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeBetween(Integer value1, Integer value2) {
            addCriterion("fcancel_type between", value1, value2, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("fcancel_type not between", value1, value2, "fcancelType");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonIsNull() {
            addCriterion("fcancel_reason is null");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonIsNotNull() {
            addCriterion("fcancel_reason is not null");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonEqualTo(String value) {
            addCriterion("fcancel_reason =", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonNotEqualTo(String value) {
            addCriterion("fcancel_reason <>", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonGreaterThan(String value) {
            addCriterion("fcancel_reason >", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonGreaterThanOrEqualTo(String value) {
            addCriterion("fcancel_reason >=", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonLessThan(String value) {
            addCriterion("fcancel_reason <", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonLessThanOrEqualTo(String value) {
            addCriterion("fcancel_reason <=", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonLike(String value) {
            addCriterion("fcancel_reason like", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonNotLike(String value) {
            addCriterion("fcancel_reason not like", value, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonIn(List<String> values) {
            addCriterion("fcancel_reason in", values, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonNotIn(List<String> values) {
            addCriterion("fcancel_reason not in", values, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonBetween(String value1, String value2) {
            addCriterion("fcancel_reason between", value1, value2, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFcancelReasonNotBetween(String value1, String value2) {
            addCriterion("fcancel_reason not between", value1, value2, "fcancelReason");
            return (Criteria) this;
        }

        public Criteria andFskuAmountIsNull() {
            addCriterion("fsku_amount is null");
            return (Criteria) this;
        }

        public Criteria andFskuAmountIsNotNull() {
            addCriterion("fsku_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFskuAmountEqualTo(Long value) {
            addCriterion("fsku_amount =", value, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountNotEqualTo(Long value) {
            addCriterion("fsku_amount <>", value, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountGreaterThan(Long value) {
            addCriterion("fsku_amount >", value, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("fsku_amount >=", value, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountLessThan(Long value) {
            addCriterion("fsku_amount <", value, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountLessThanOrEqualTo(Long value) {
            addCriterion("fsku_amount <=", value, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountIn(List<Long> values) {
            addCriterion("fsku_amount in", values, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountNotIn(List<Long> values) {
            addCriterion("fsku_amount not in", values, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountBetween(Long value1, Long value2) {
            addCriterion("fsku_amount between", value1, value2, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andFskuAmountNotBetween(Long value1, Long value2) {
            addCriterion("fsku_amount not between", value1, value2, "fskuAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountIsNull() {
            addCriterion("forder_discount_amount is null");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountIsNotNull() {
            addCriterion("forder_discount_amount is not null");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountEqualTo(Long value) {
            addCriterion("forder_discount_amount =", value, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountNotEqualTo(Long value) {
            addCriterion("forder_discount_amount <>", value, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountGreaterThan(Long value) {
            addCriterion("forder_discount_amount >", value, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("forder_discount_amount >=", value, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountLessThan(Long value) {
            addCriterion("forder_discount_amount <", value, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountLessThanOrEqualTo(Long value) {
            addCriterion("forder_discount_amount <=", value, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountIn(List<Long> values) {
            addCriterion("forder_discount_amount in", values, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountNotIn(List<Long> values) {
            addCriterion("forder_discount_amount not in", values, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountBetween(Long value1, Long value2) {
            addCriterion("forder_discount_amount between", value1, value2, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andForderDiscountAmountNotBetween(Long value1, Long value2) {
            addCriterion("forder_discount_amount not between", value1, value2, "forderDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountIsNull() {
            addCriterion("ftax_amount is null");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountIsNotNull() {
            addCriterion("ftax_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountEqualTo(Long value) {
            addCriterion("ftax_amount =", value, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountNotEqualTo(Long value) {
            addCriterion("ftax_amount <>", value, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountGreaterThan(Long value) {
            addCriterion("ftax_amount >", value, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("ftax_amount >=", value, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountLessThan(Long value) {
            addCriterion("ftax_amount <", value, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountLessThanOrEqualTo(Long value) {
            addCriterion("ftax_amount <=", value, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountIn(List<Long> values) {
            addCriterion("ftax_amount in", values, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountNotIn(List<Long> values) {
            addCriterion("ftax_amount not in", values, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountBetween(Long value1, Long value2) {
            addCriterion("ftax_amount between", value1, value2, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFtaxAmountNotBetween(Long value1, Long value2) {
            addCriterion("ftax_amount not between", value1, value2, "ftaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountIsNull() {
            addCriterion("ffreight_amount is null");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountIsNotNull() {
            addCriterion("ffreight_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountEqualTo(Long value) {
            addCriterion("ffreight_amount =", value, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountNotEqualTo(Long value) {
            addCriterion("ffreight_amount <>", value, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountGreaterThan(Long value) {
            addCriterion("ffreight_amount >", value, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("ffreight_amount >=", value, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountLessThan(Long value) {
            addCriterion("ffreight_amount <", value, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountLessThanOrEqualTo(Long value) {
            addCriterion("ffreight_amount <=", value, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountIn(List<Long> values) {
            addCriterion("ffreight_amount in", values, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountNotIn(List<Long> values) {
            addCriterion("ffreight_amount not in", values, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountBetween(Long value1, Long value2) {
            addCriterion("ffreight_amount between", value1, value2, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightAmountNotBetween(Long value1, Long value2) {
            addCriterion("ffreight_amount not between", value1, value2, "ffreightAmount");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeIsNull() {
            addCriterion("fbuy_agent_income is null");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeIsNotNull() {
            addCriterion("fbuy_agent_income is not null");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeEqualTo(Long value) {
            addCriterion("fbuy_agent_income =", value, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeNotEqualTo(Long value) {
            addCriterion("fbuy_agent_income <>", value, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeGreaterThan(Long value) {
            addCriterion("fbuy_agent_income >", value, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeGreaterThanOrEqualTo(Long value) {
            addCriterion("fbuy_agent_income >=", value, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeLessThan(Long value) {
            addCriterion("fbuy_agent_income <", value, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeLessThanOrEqualTo(Long value) {
            addCriterion("fbuy_agent_income <=", value, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeIn(List<Long> values) {
            addCriterion("fbuy_agent_income in", values, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeNotIn(List<Long> values) {
            addCriterion("fbuy_agent_income not in", values, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeBetween(Long value1, Long value2) {
            addCriterion("fbuy_agent_income between", value1, value2, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFbuyAgentIncomeNotBetween(Long value1, Long value2) {
            addCriterion("fbuy_agent_income not between", value1, value2, "fbuyAgentIncome");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceIsNull() {
            addCriterion("ftax_difference is null");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceIsNotNull() {
            addCriterion("ftax_difference is not null");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceEqualTo(Long value) {
            addCriterion("ftax_difference =", value, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceNotEqualTo(Long value) {
            addCriterion("ftax_difference <>", value, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceGreaterThan(Long value) {
            addCriterion("ftax_difference >", value, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceGreaterThanOrEqualTo(Long value) {
            addCriterion("ftax_difference >=", value, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceLessThan(Long value) {
            addCriterion("ftax_difference <", value, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceLessThanOrEqualTo(Long value) {
            addCriterion("ftax_difference <=", value, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceIn(List<Long> values) {
            addCriterion("ftax_difference in", values, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceNotIn(List<Long> values) {
            addCriterion("ftax_difference not in", values, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceBetween(Long value1, Long value2) {
            addCriterion("ftax_difference between", value1, value2, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andFtaxDifferenceNotBetween(Long value1, Long value2) {
            addCriterion("ftax_difference not between", value1, value2, "ftaxDifference");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountIsNull() {
            addCriterion("forder_real_amount is null");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountIsNotNull() {
            addCriterion("forder_real_amount is not null");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountEqualTo(Long value) {
            addCriterion("forder_real_amount =", value, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountNotEqualTo(Long value) {
            addCriterion("forder_real_amount <>", value, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountGreaterThan(Long value) {
            addCriterion("forder_real_amount >", value, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("forder_real_amount >=", value, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountLessThan(Long value) {
            addCriterion("forder_real_amount <", value, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountLessThanOrEqualTo(Long value) {
            addCriterion("forder_real_amount <=", value, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountIn(List<Long> values) {
            addCriterion("forder_real_amount in", values, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountNotIn(List<Long> values) {
            addCriterion("forder_real_amount not in", values, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountBetween(Long value1, Long value2) {
            addCriterion("forder_real_amount between", value1, value2, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderRealAmountNotBetween(Long value1, Long value2) {
            addCriterion("forder_real_amount not between", value1, value2, "forderRealAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountIsNull() {
            addCriterion("forder_amount is null");
            return (Criteria) this;
        }

        public Criteria andForderAmountIsNotNull() {
            addCriterion("forder_amount is not null");
            return (Criteria) this;
        }

        public Criteria andForderAmountEqualTo(Long value) {
            addCriterion("forder_amount =", value, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountNotEqualTo(Long value) {
            addCriterion("forder_amount <>", value, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountGreaterThan(Long value) {
            addCriterion("forder_amount >", value, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("forder_amount >=", value, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountLessThan(Long value) {
            addCriterion("forder_amount <", value, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountLessThanOrEqualTo(Long value) {
            addCriterion("forder_amount <=", value, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountIn(List<Long> values) {
            addCriterion("forder_amount in", values, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountNotIn(List<Long> values) {
            addCriterion("forder_amount not in", values, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountBetween(Long value1, Long value2) {
            addCriterion("forder_amount between", value1, value2, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andForderAmountNotBetween(Long value1, Long value2) {
            addCriterion("forder_amount not between", value1, value2, "forderAmount");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeIsNull() {
            addCriterion("fconfirm_time is null");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeIsNotNull() {
            addCriterion("fconfirm_time is not null");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeEqualTo(Date value) {
            addCriterion("fconfirm_time =", value, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeNotEqualTo(Date value) {
            addCriterion("fconfirm_time <>", value, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeGreaterThan(Date value) {
            addCriterion("fconfirm_time >", value, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fconfirm_time >=", value, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeLessThan(Date value) {
            addCriterion("fconfirm_time <", value, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("fconfirm_time <=", value, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeIn(List<Date> values) {
            addCriterion("fconfirm_time in", values, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeNotIn(List<Date> values) {
            addCriterion("fconfirm_time not in", values, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeBetween(Date value1, Date value2) {
            addCriterion("fconfirm_time between", value1, value2, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFconfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("fconfirm_time not between", value1, value2, "fconfirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeIsNull() {
            addCriterion("faffirm_time is null");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeIsNotNull() {
            addCriterion("faffirm_time is not null");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeEqualTo(Date value) {
            addCriterion("faffirm_time =", value, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeNotEqualTo(Date value) {
            addCriterion("faffirm_time <>", value, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeGreaterThan(Date value) {
            addCriterion("faffirm_time >", value, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("faffirm_time >=", value, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeLessThan(Date value) {
            addCriterion("faffirm_time <", value, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("faffirm_time <=", value, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeIn(List<Date> values) {
            addCriterion("faffirm_time in", values, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeNotIn(List<Date> values) {
            addCriterion("faffirm_time not in", values, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeBetween(Date value1, Date value2) {
            addCriterion("faffirm_time between", value1, value2, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFaffirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("faffirm_time not between", value1, value2, "faffirmTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeIsNull() {
            addCriterion("fpush_time is null");
            return (Criteria) this;
        }

        public Criteria andFpushTimeIsNotNull() {
            addCriterion("fpush_time is not null");
            return (Criteria) this;
        }

        public Criteria andFpushTimeEqualTo(Date value) {
            addCriterion("fpush_time =", value, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeNotEqualTo(Date value) {
            addCriterion("fpush_time <>", value, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeGreaterThan(Date value) {
            addCriterion("fpush_time >", value, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fpush_time >=", value, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeLessThan(Date value) {
            addCriterion("fpush_time <", value, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeLessThanOrEqualTo(Date value) {
            addCriterion("fpush_time <=", value, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeIn(List<Date> values) {
            addCriterion("fpush_time in", values, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeNotIn(List<Date> values) {
            addCriterion("fpush_time not in", values, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeBetween(Date value1, Date value2) {
            addCriterion("fpush_time between", value1, value2, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFpushTimeNotBetween(Date value1, Date value2) {
            addCriterion("fpush_time not between", value1, value2, "fpushTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIsNull() {
            addCriterion("fcreate_time is null");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIsNotNull() {
            addCriterion("fcreate_time is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeEqualTo(Date value) {
            addCriterion("fcreate_time =", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotEqualTo(Date value) {
            addCriterion("fcreate_time <>", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeGreaterThan(Date value) {
            addCriterion("fcreate_time >", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fcreate_time >=", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeLessThan(Date value) {
            addCriterion("fcreate_time <", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("fcreate_time <=", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIn(List<Date> values) {
            addCriterion("fcreate_time in", values, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotIn(List<Date> values) {
            addCriterion("fcreate_time not in", values, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeBetween(Date value1, Date value2) {
            addCriterion("fcreate_time between", value1, value2, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("fcreate_time not between", value1, value2, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIsNull() {
            addCriterion("fmodify_time is null");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIsNotNull() {
            addCriterion("fmodify_time is not null");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeEqualTo(Date value) {
            addCriterion("fmodify_time =", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotEqualTo(Date value) {
            addCriterion("fmodify_time <>", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeGreaterThan(Date value) {
            addCriterion("fmodify_time >", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fmodify_time >=", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeLessThan(Date value) {
            addCriterion("fmodify_time <", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("fmodify_time <=", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIn(List<Date> values) {
            addCriterion("fmodify_time in", values, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotIn(List<Date> values) {
            addCriterion("fmodify_time not in", values, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeBetween(Date value1, Date value2) {
            addCriterion("fmodify_time between", value1, value2, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("fmodify_time not between", value1, value2, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountIsNull() {
            addCriterion("ffreight_tax_amount is null");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountIsNotNull() {
            addCriterion("ffreight_tax_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountEqualTo(Long value) {
            addCriterion("ffreight_tax_amount =", value, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountNotEqualTo(Long value) {
            addCriterion("ffreight_tax_amount <>", value, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountGreaterThan(Long value) {
            addCriterion("ffreight_tax_amount >", value, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("ffreight_tax_amount >=", value, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountLessThan(Long value) {
            addCriterion("ffreight_tax_amount <", value, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountLessThanOrEqualTo(Long value) {
            addCriterion("ffreight_tax_amount <=", value, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountIn(List<Long> values) {
            addCriterion("ffreight_tax_amount in", values, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountNotIn(List<Long> values) {
            addCriterion("ffreight_tax_amount not in", values, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountBetween(Long value1, Long value2) {
            addCriterion("ffreight_tax_amount between", value1, value2, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFfreightTaxAmountNotBetween(Long value1, Long value2) {
            addCriterion("ffreight_tax_amount not between", value1, value2, "ffreightTaxAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountIsNull() {
            addCriterion("fpurchase_amount is null");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountIsNotNull() {
            addCriterion("fpurchase_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountEqualTo(Long value) {
            addCriterion("fpurchase_amount =", value, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountNotEqualTo(Long value) {
            addCriterion("fpurchase_amount <>", value, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountGreaterThan(Long value) {
            addCriterion("fpurchase_amount >", value, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("fpurchase_amount >=", value, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountLessThan(Long value) {
            addCriterion("fpurchase_amount <", value, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountLessThanOrEqualTo(Long value) {
            addCriterion("fpurchase_amount <=", value, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountIn(List<Long> values) {
            addCriterion("fpurchase_amount in", values, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountNotIn(List<Long> values) {
            addCriterion("fpurchase_amount not in", values, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountBetween(Long value1, Long value2) {
            addCriterion("fpurchase_amount between", value1, value2, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFpurchaseAmountNotBetween(Long value1, Long value2) {
            addCriterion("fpurchase_amount not between", value1, value2, "fpurchaseAmount");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeIsNull() {
            addCriterion("fbonded_order_type is null");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeIsNotNull() {
            addCriterion("fbonded_order_type is not null");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeEqualTo(Integer value) {
            addCriterion("fbonded_order_type =", value, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeNotEqualTo(Integer value) {
            addCriterion("fbonded_order_type <>", value, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeGreaterThan(Integer value) {
            addCriterion("fbonded_order_type >", value, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fbonded_order_type >=", value, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeLessThan(Integer value) {
            addCriterion("fbonded_order_type <", value, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeLessThanOrEqualTo(Integer value) {
            addCriterion("fbonded_order_type <=", value, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeIn(List<Integer> values) {
            addCriterion("fbonded_order_type in", values, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeNotIn(List<Integer> values) {
            addCriterion("fbonded_order_type not in", values, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeBetween(Integer value1, Integer value2) {
            addCriterion("fbonded_order_type between", value1, value2, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andFbondedOrderTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("fbonded_order_type not between", value1, value2, "fbondedOrderType");
            return (Criteria) this;
        }

        public Criteria andForderRemarkIsNull() {
            addCriterion("forder_remark is null");
            return (Criteria) this;
        }

        public Criteria andForderRemarkIsNotNull() {
            addCriterion("forder_remark is not null");
            return (Criteria) this;
        }

        public Criteria andForderRemarkEqualTo(String value) {
            addCriterion("forder_remark =", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkNotEqualTo(String value) {
            addCriterion("forder_remark <>", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkGreaterThan(String value) {
            addCriterion("forder_remark >", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("forder_remark >=", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkLessThan(String value) {
            addCriterion("forder_remark <", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkLessThanOrEqualTo(String value) {
            addCriterion("forder_remark <=", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkLike(String value) {
            addCriterion("forder_remark like", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkNotLike(String value) {
            addCriterion("forder_remark not like", value, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkIn(List<String> values) {
            addCriterion("forder_remark in", values, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkNotIn(List<String> values) {
            addCriterion("forder_remark not in", values, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkBetween(String value1, String value2) {
            addCriterion("forder_remark between", value1, value2, "forderRemark");
            return (Criteria) this;
        }

        public Criteria andForderRemarkNotBetween(String value1, String value2) {
            addCriterion("forder_remark not between", value1, value2, "forderRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_order
     *
     *   do_not_delete_during_merge Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_order
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}