package org.you.oops.order.domain.userorder.repository.po;

import java.util.Date;

public class BbcOrderPaymentPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_payment_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String forderPaymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fuid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_delivery_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long forderDeliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_source
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Integer forderSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Integer forderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Integer forderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_pay_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Integer forderPayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_thirdpay_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Integer forderThirdpayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fbalance_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fbalancePayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcredit_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fcreditPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fthird_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fthirdPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_sku_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalSkuAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_freight_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalFreightAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_tax_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalTaxAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_tax_difference
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalTaxDifference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_agent_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalAgentAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_agent_income
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalAgentIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_real_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalRealAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.ftotal_order_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long ftotalOrderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fthird_trade_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fthirdTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fthird_trade_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Integer fthirdTradeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpay_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpayNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpay_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpayer_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpayerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpayer_card_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpayerCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpay_card_url_front
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpayCardUrlFront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpay_card_url_back
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpayCardUrlBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_province_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fdeliveryProvinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_province
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_city_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fdeliveryCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_city
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_area_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fdeliveryAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_area
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_addr
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_postcode
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_mobile
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fdelivery_cardid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fdeliveryCardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcard_url_front
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fcardUrlFront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcard_url_back
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fcardUrlBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpay_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Date fpayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcoupon_receive_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fcouponReceiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.flock_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Date flockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcreate_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Date fcreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fmodify_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Date fmodifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fpayment_parent_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpaymentParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fplatform_order_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fplatformOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fplatform_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fplatformName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fchannel_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fchannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fshop_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fshopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fchannel_order_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Integer fchannelOrderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fchannel_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fchannelDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fplatform_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fplatformDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcustom_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fcustomNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fplatform_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fplatformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcustoms_record_number
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fcustomsRecordNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.fcustoms_record_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fcustomsRecordName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_order_payment.forder_desc
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String forderDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_payment_id
     *
     * @return the value of t_bbc_order_payment.forder_payment_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getForderPaymentId() {
        return forderPaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_payment_id
     *
     * @param forderPaymentId the value for t_bbc_order_payment.forder_payment_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderPaymentId(String forderPaymentId) {
        this.forderPaymentId = forderPaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fuid
     *
     * @return the value of t_bbc_order_payment.fuid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFuid() {
        return fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fuid
     *
     * @param fuid the value for t_bbc_order_payment.fuid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFuid(Long fuid) {
        this.fuid = fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_delivery_id
     *
     * @return the value of t_bbc_order_payment.forder_delivery_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getForderDeliveryId() {
        return forderDeliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_delivery_id
     *
     * @param forderDeliveryId the value for t_bbc_order_payment.forder_delivery_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderDeliveryId(Long forderDeliveryId) {
        this.forderDeliveryId = forderDeliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_source
     *
     * @return the value of t_bbc_order_payment.forder_source
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Integer getForderSource() {
        return forderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_source
     *
     * @param forderSource the value for t_bbc_order_payment.forder_source
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderSource(Integer forderSource) {
        this.forderSource = forderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_type
     *
     * @return the value of t_bbc_order_payment.forder_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Integer getForderType() {
        return forderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_type
     *
     * @param forderType the value for t_bbc_order_payment.forder_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderType(Integer forderType) {
        this.forderType = forderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_status
     *
     * @return the value of t_bbc_order_payment.forder_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Integer getForderStatus() {
        return forderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_status
     *
     * @param forderStatus the value for t_bbc_order_payment.forder_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderStatus(Integer forderStatus) {
        this.forderStatus = forderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_pay_type
     *
     * @return the value of t_bbc_order_payment.forder_pay_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Integer getForderPayType() {
        return forderPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_pay_type
     *
     * @param forderPayType the value for t_bbc_order_payment.forder_pay_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderPayType(Integer forderPayType) {
        this.forderPayType = forderPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_thirdpay_type
     *
     * @return the value of t_bbc_order_payment.forder_thirdpay_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Integer getForderThirdpayType() {
        return forderThirdpayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_thirdpay_type
     *
     * @param forderThirdpayType the value for t_bbc_order_payment.forder_thirdpay_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderThirdpayType(Integer forderThirdpayType) {
        this.forderThirdpayType = forderThirdpayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fbalance_pay_amount
     *
     * @return the value of t_bbc_order_payment.fbalance_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFbalancePayAmount() {
        return fbalancePayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fbalance_pay_amount
     *
     * @param fbalancePayAmount the value for t_bbc_order_payment.fbalance_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFbalancePayAmount(Long fbalancePayAmount) {
        this.fbalancePayAmount = fbalancePayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcredit_pay_amount
     *
     * @return the value of t_bbc_order_payment.fcredit_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFcreditPayAmount() {
        return fcreditPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcredit_pay_amount
     *
     * @param fcreditPayAmount the value for t_bbc_order_payment.fcredit_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcreditPayAmount(Long fcreditPayAmount) {
        this.fcreditPayAmount = fcreditPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fthird_pay_amount
     *
     * @return the value of t_bbc_order_payment.fthird_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFthirdPayAmount() {
        return fthirdPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fthird_pay_amount
     *
     * @param fthirdPayAmount the value for t_bbc_order_payment.fthird_pay_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFthirdPayAmount(Long fthirdPayAmount) {
        this.fthirdPayAmount = fthirdPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_sku_amount
     *
     * @return the value of t_bbc_order_payment.ftotal_sku_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalSkuAmount() {
        return ftotalSkuAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_sku_amount
     *
     * @param ftotalSkuAmount the value for t_bbc_order_payment.ftotal_sku_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalSkuAmount(Long ftotalSkuAmount) {
        this.ftotalSkuAmount = ftotalSkuAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_freight_amount
     *
     * @return the value of t_bbc_order_payment.ftotal_freight_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalFreightAmount() {
        return ftotalFreightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_freight_amount
     *
     * @param ftotalFreightAmount the value for t_bbc_order_payment.ftotal_freight_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalFreightAmount(Long ftotalFreightAmount) {
        this.ftotalFreightAmount = ftotalFreightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_tax_amount
     *
     * @return the value of t_bbc_order_payment.ftotal_tax_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalTaxAmount() {
        return ftotalTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_tax_amount
     *
     * @param ftotalTaxAmount the value for t_bbc_order_payment.ftotal_tax_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalTaxAmount(Long ftotalTaxAmount) {
        this.ftotalTaxAmount = ftotalTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_discount_amount
     *
     * @return the value of t_bbc_order_payment.ftotal_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalDiscountAmount() {
        return ftotalDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_discount_amount
     *
     * @param ftotalDiscountAmount the value for t_bbc_order_payment.ftotal_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalDiscountAmount(Long ftotalDiscountAmount) {
        this.ftotalDiscountAmount = ftotalDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_tax_difference
     *
     * @return the value of t_bbc_order_payment.ftotal_tax_difference
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalTaxDifference() {
        return ftotalTaxDifference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_tax_difference
     *
     * @param ftotalTaxDifference the value for t_bbc_order_payment.ftotal_tax_difference
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalTaxDifference(Long ftotalTaxDifference) {
        this.ftotalTaxDifference = ftotalTaxDifference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_agent_amount
     *
     * @return the value of t_bbc_order_payment.ftotal_agent_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalAgentAmount() {
        return ftotalAgentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_agent_amount
     *
     * @param ftotalAgentAmount the value for t_bbc_order_payment.ftotal_agent_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalAgentAmount(Long ftotalAgentAmount) {
        this.ftotalAgentAmount = ftotalAgentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_agent_income
     *
     * @return the value of t_bbc_order_payment.ftotal_agent_income
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalAgentIncome() {
        return ftotalAgentIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_agent_income
     *
     * @param ftotalAgentIncome the value for t_bbc_order_payment.ftotal_agent_income
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalAgentIncome(Long ftotalAgentIncome) {
        this.ftotalAgentIncome = ftotalAgentIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_real_amount
     *
     * @return the value of t_bbc_order_payment.ftotal_real_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalRealAmount() {
        return ftotalRealAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_real_amount
     *
     * @param ftotalRealAmount the value for t_bbc_order_payment.ftotal_real_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalRealAmount(Long ftotalRealAmount) {
        this.ftotalRealAmount = ftotalRealAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.ftotal_order_amount
     *
     * @return the value of t_bbc_order_payment.ftotal_order_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFtotalOrderAmount() {
        return ftotalOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.ftotal_order_amount
     *
     * @param ftotalOrderAmount the value for t_bbc_order_payment.ftotal_order_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtotalOrderAmount(Long ftotalOrderAmount) {
        this.ftotalOrderAmount = ftotalOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fthird_trade_no
     *
     * @return the value of t_bbc_order_payment.fthird_trade_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFthirdTradeNo() {
        return fthirdTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fthird_trade_no
     *
     * @param fthirdTradeNo the value for t_bbc_order_payment.fthird_trade_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFthirdTradeNo(String fthirdTradeNo) {
        this.fthirdTradeNo = fthirdTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fthird_trade_status
     *
     * @return the value of t_bbc_order_payment.fthird_trade_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Integer getFthirdTradeStatus() {
        return fthirdTradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fthird_trade_status
     *
     * @param fthirdTradeStatus the value for t_bbc_order_payment.fthird_trade_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFthirdTradeStatus(Integer fthirdTradeStatus) {
        this.fthirdTradeStatus = fthirdTradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpay_no
     *
     * @return the value of t_bbc_order_payment.fpay_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpayNo() {
        return fpayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpay_no
     *
     * @param fpayNo the value for t_bbc_order_payment.fpay_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpayNo(String fpayNo) {
        this.fpayNo = fpayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpay_name
     *
     * @return the value of t_bbc_order_payment.fpay_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpayName() {
        return fpayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpay_name
     *
     * @param fpayName the value for t_bbc_order_payment.fpay_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpayName(String fpayName) {
        this.fpayName = fpayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpayer_name
     *
     * @return the value of t_bbc_order_payment.fpayer_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpayerName() {
        return fpayerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpayer_name
     *
     * @param fpayerName the value for t_bbc_order_payment.fpayer_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpayerName(String fpayerName) {
        this.fpayerName = fpayerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpayer_card_id
     *
     * @return the value of t_bbc_order_payment.fpayer_card_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpayerCardId() {
        return fpayerCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpayer_card_id
     *
     * @param fpayerCardId the value for t_bbc_order_payment.fpayer_card_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpayerCardId(String fpayerCardId) {
        this.fpayerCardId = fpayerCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpay_card_url_front
     *
     * @return the value of t_bbc_order_payment.fpay_card_url_front
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpayCardUrlFront() {
        return fpayCardUrlFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpay_card_url_front
     *
     * @param fpayCardUrlFront the value for t_bbc_order_payment.fpay_card_url_front
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpayCardUrlFront(String fpayCardUrlFront) {
        this.fpayCardUrlFront = fpayCardUrlFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpay_card_url_back
     *
     * @return the value of t_bbc_order_payment.fpay_card_url_back
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpayCardUrlBack() {
        return fpayCardUrlBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpay_card_url_back
     *
     * @param fpayCardUrlBack the value for t_bbc_order_payment.fpay_card_url_back
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpayCardUrlBack(String fpayCardUrlBack) {
        this.fpayCardUrlBack = fpayCardUrlBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_name
     *
     * @return the value of t_bbc_order_payment.fdelivery_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryName() {
        return fdeliveryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_name
     *
     * @param fdeliveryName the value for t_bbc_order_payment.fdelivery_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryName(String fdeliveryName) {
        this.fdeliveryName = fdeliveryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_province_id
     *
     * @return the value of t_bbc_order_payment.fdelivery_province_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFdeliveryProvinceId() {
        return fdeliveryProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_province_id
     *
     * @param fdeliveryProvinceId the value for t_bbc_order_payment.fdelivery_province_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryProvinceId(Long fdeliveryProvinceId) {
        this.fdeliveryProvinceId = fdeliveryProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_province
     *
     * @return the value of t_bbc_order_payment.fdelivery_province
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryProvince() {
        return fdeliveryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_province
     *
     * @param fdeliveryProvince the value for t_bbc_order_payment.fdelivery_province
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryProvince(String fdeliveryProvince) {
        this.fdeliveryProvince = fdeliveryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_city_id
     *
     * @return the value of t_bbc_order_payment.fdelivery_city_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFdeliveryCityId() {
        return fdeliveryCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_city_id
     *
     * @param fdeliveryCityId the value for t_bbc_order_payment.fdelivery_city_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryCityId(Long fdeliveryCityId) {
        this.fdeliveryCityId = fdeliveryCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_city
     *
     * @return the value of t_bbc_order_payment.fdelivery_city
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryCity() {
        return fdeliveryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_city
     *
     * @param fdeliveryCity the value for t_bbc_order_payment.fdelivery_city
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryCity(String fdeliveryCity) {
        this.fdeliveryCity = fdeliveryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_area_id
     *
     * @return the value of t_bbc_order_payment.fdelivery_area_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFdeliveryAreaId() {
        return fdeliveryAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_area_id
     *
     * @param fdeliveryAreaId the value for t_bbc_order_payment.fdelivery_area_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryAreaId(Long fdeliveryAreaId) {
        this.fdeliveryAreaId = fdeliveryAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_area
     *
     * @return the value of t_bbc_order_payment.fdelivery_area
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryArea() {
        return fdeliveryArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_area
     *
     * @param fdeliveryArea the value for t_bbc_order_payment.fdelivery_area
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryArea(String fdeliveryArea) {
        this.fdeliveryArea = fdeliveryArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_addr
     *
     * @return the value of t_bbc_order_payment.fdelivery_addr
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryAddr() {
        return fdeliveryAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_addr
     *
     * @param fdeliveryAddr the value for t_bbc_order_payment.fdelivery_addr
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryAddr(String fdeliveryAddr) {
        this.fdeliveryAddr = fdeliveryAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_postcode
     *
     * @return the value of t_bbc_order_payment.fdelivery_postcode
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryPostcode() {
        return fdeliveryPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_postcode
     *
     * @param fdeliveryPostcode the value for t_bbc_order_payment.fdelivery_postcode
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryPostcode(String fdeliveryPostcode) {
        this.fdeliveryPostcode = fdeliveryPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_mobile
     *
     * @return the value of t_bbc_order_payment.fdelivery_mobile
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryMobile() {
        return fdeliveryMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_mobile
     *
     * @param fdeliveryMobile the value for t_bbc_order_payment.fdelivery_mobile
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryMobile(String fdeliveryMobile) {
        this.fdeliveryMobile = fdeliveryMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fdelivery_cardid
     *
     * @return the value of t_bbc_order_payment.fdelivery_cardid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFdeliveryCardid() {
        return fdeliveryCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fdelivery_cardid
     *
     * @param fdeliveryCardid the value for t_bbc_order_payment.fdelivery_cardid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFdeliveryCardid(String fdeliveryCardid) {
        this.fdeliveryCardid = fdeliveryCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcard_url_front
     *
     * @return the value of t_bbc_order_payment.fcard_url_front
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFcardUrlFront() {
        return fcardUrlFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcard_url_front
     *
     * @param fcardUrlFront the value for t_bbc_order_payment.fcard_url_front
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcardUrlFront(String fcardUrlFront) {
        this.fcardUrlFront = fcardUrlFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcard_url_back
     *
     * @return the value of t_bbc_order_payment.fcard_url_back
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFcardUrlBack() {
        return fcardUrlBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcard_url_back
     *
     * @param fcardUrlBack the value for t_bbc_order_payment.fcard_url_back
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcardUrlBack(String fcardUrlBack) {
        this.fcardUrlBack = fcardUrlBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpay_time
     *
     * @return the value of t_bbc_order_payment.fpay_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Date getFpayTime() {
        return fpayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpay_time
     *
     * @param fpayTime the value for t_bbc_order_payment.fpay_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpayTime(Date fpayTime) {
        this.fpayTime = fpayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcoupon_receive_id
     *
     * @return the value of t_bbc_order_payment.fcoupon_receive_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFcouponReceiveId() {
        return fcouponReceiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcoupon_receive_id
     *
     * @param fcouponReceiveId the value for t_bbc_order_payment.fcoupon_receive_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcouponReceiveId(Long fcouponReceiveId) {
        this.fcouponReceiveId = fcouponReceiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.flock_time
     *
     * @return the value of t_bbc_order_payment.flock_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Date getFlockTime() {
        return flockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.flock_time
     *
     * @param flockTime the value for t_bbc_order_payment.flock_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFlockTime(Date flockTime) {
        this.flockTime = flockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcreate_time
     *
     * @return the value of t_bbc_order_payment.fcreate_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Date getFcreateTime() {
        return fcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcreate_time
     *
     * @param fcreateTime the value for t_bbc_order_payment.fcreate_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcreateTime(Date fcreateTime) {
        this.fcreateTime = fcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fmodify_time
     *
     * @return the value of t_bbc_order_payment.fmodify_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Date getFmodifyTime() {
        return fmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fmodify_time
     *
     * @param fmodifyTime the value for t_bbc_order_payment.fmodify_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFmodifyTime(Date fmodifyTime) {
        this.fmodifyTime = fmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fpayment_parent_id
     *
     * @return the value of t_bbc_order_payment.fpayment_parent_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpaymentParentId() {
        return fpaymentParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fpayment_parent_id
     *
     * @param fpaymentParentId the value for t_bbc_order_payment.fpayment_parent_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpaymentParentId(String fpaymentParentId) {
        this.fpaymentParentId = fpaymentParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fplatform_order_no
     *
     * @return the value of t_bbc_order_payment.fplatform_order_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFplatformOrderNo() {
        return fplatformOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fplatform_order_no
     *
     * @param fplatformOrderNo the value for t_bbc_order_payment.fplatform_order_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFplatformOrderNo(String fplatformOrderNo) {
        this.fplatformOrderNo = fplatformOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fplatform_name
     *
     * @return the value of t_bbc_order_payment.fplatform_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFplatformName() {
        return fplatformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fplatform_name
     *
     * @param fplatformName the value for t_bbc_order_payment.fplatform_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFplatformName(String fplatformName) {
        this.fplatformName = fplatformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fchannel_id
     *
     * @return the value of t_bbc_order_payment.fchannel_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFchannelId() {
        return fchannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fchannel_id
     *
     * @param fchannelId the value for t_bbc_order_payment.fchannel_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFchannelId(Long fchannelId) {
        this.fchannelId = fchannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fshop_id
     *
     * @return the value of t_bbc_order_payment.fshop_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFshopId() {
        return fshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fshop_id
     *
     * @param fshopId the value for t_bbc_order_payment.fshop_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFshopId(Long fshopId) {
        this.fshopId = fshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fchannel_order_type
     *
     * @return the value of t_bbc_order_payment.fchannel_order_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Integer getFchannelOrderType() {
        return fchannelOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fchannel_order_type
     *
     * @param fchannelOrderType the value for t_bbc_order_payment.fchannel_order_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFchannelOrderType(Integer fchannelOrderType) {
        this.fchannelOrderType = fchannelOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fchannel_discount_amount
     *
     * @return the value of t_bbc_order_payment.fchannel_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFchannelDiscountAmount() {
        return fchannelDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fchannel_discount_amount
     *
     * @param fchannelDiscountAmount the value for t_bbc_order_payment.fchannel_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFchannelDiscountAmount(Long fchannelDiscountAmount) {
        this.fchannelDiscountAmount = fchannelDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fplatform_discount_amount
     *
     * @return the value of t_bbc_order_payment.fplatform_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFplatformDiscountAmount() {
        return fplatformDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fplatform_discount_amount
     *
     * @param fplatformDiscountAmount the value for t_bbc_order_payment.fplatform_discount_amount
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFplatformDiscountAmount(Long fplatformDiscountAmount) {
        this.fplatformDiscountAmount = fplatformDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcustom_no
     *
     * @return the value of t_bbc_order_payment.fcustom_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFcustomNo() {
        return fcustomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcustom_no
     *
     * @param fcustomNo the value for t_bbc_order_payment.fcustom_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcustomNo(String fcustomNo) {
        this.fcustomNo = fcustomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fplatform_id
     *
     * @return the value of t_bbc_order_payment.fplatform_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFplatformId() {
        return fplatformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fplatform_id
     *
     * @param fplatformId the value for t_bbc_order_payment.fplatform_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFplatformId(Long fplatformId) {
        this.fplatformId = fplatformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcustoms_record_number
     *
     * @return the value of t_bbc_order_payment.fcustoms_record_number
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFcustomsRecordNumber() {
        return fcustomsRecordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcustoms_record_number
     *
     * @param fcustomsRecordNumber the value for t_bbc_order_payment.fcustoms_record_number
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcustomsRecordNumber(String fcustomsRecordNumber) {
        this.fcustomsRecordNumber = fcustomsRecordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.fcustoms_record_name
     *
     * @return the value of t_bbc_order_payment.fcustoms_record_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFcustomsRecordName() {
        return fcustomsRecordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.fcustoms_record_name
     *
     * @param fcustomsRecordName the value for t_bbc_order_payment.fcustoms_record_name
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFcustomsRecordName(String fcustomsRecordName) {
        this.fcustomsRecordName = fcustomsRecordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_order_payment.forder_desc
     *
     * @return the value of t_bbc_order_payment.forder_desc
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getForderDesc() {
        return forderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_order_payment.forder_desc
     *
     * @param forderDesc the value for t_bbc_order_payment.forder_desc
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setForderDesc(String forderDesc) {
        this.forderDesc = forderDesc;
    }
}