package org.you.oops.order.domain.userorder.repository.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BbcUserAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public BbcUserAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFuidIsNull() {
            addCriterion("fuid is null");
            return (Criteria) this;
        }

        public Criteria andFuidIsNotNull() {
            addCriterion("fuid is not null");
            return (Criteria) this;
        }

        public Criteria andFuidEqualTo(Long value) {
            addCriterion("fuid =", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidNotEqualTo(Long value) {
            addCriterion("fuid <>", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidGreaterThan(Long value) {
            addCriterion("fuid >", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidGreaterThanOrEqualTo(Long value) {
            addCriterion("fuid >=", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidLessThan(Long value) {
            addCriterion("fuid <", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidLessThanOrEqualTo(Long value) {
            addCriterion("fuid <=", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidIn(List<Long> values) {
            addCriterion("fuid in", values, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidNotIn(List<Long> values) {
            addCriterion("fuid not in", values, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidBetween(Long value1, Long value2) {
            addCriterion("fuid between", value1, value2, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidNotBetween(Long value1, Long value2) {
            addCriterion("fuid not between", value1, value2, "fuid");
            return (Criteria) this;
        }

        public Criteria andFbalanceIsNull() {
            addCriterion("fbalance is null");
            return (Criteria) this;
        }

        public Criteria andFbalanceIsNotNull() {
            addCriterion("fbalance is not null");
            return (Criteria) this;
        }

        public Criteria andFbalanceEqualTo(Long value) {
            addCriterion("fbalance =", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceNotEqualTo(Long value) {
            addCriterion("fbalance <>", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceGreaterThan(Long value) {
            addCriterion("fbalance >", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("fbalance >=", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceLessThan(Long value) {
            addCriterion("fbalance <", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceLessThanOrEqualTo(Long value) {
            addCriterion("fbalance <=", value, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceIn(List<Long> values) {
            addCriterion("fbalance in", values, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceNotIn(List<Long> values) {
            addCriterion("fbalance not in", values, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceBetween(Long value1, Long value2) {
            addCriterion("fbalance between", value1, value2, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFbalanceNotBetween(Long value1, Long value2) {
            addCriterion("fbalance not between", value1, value2, "fbalance");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeIsNull() {
            addCriterion("fpenging_income is null");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeIsNotNull() {
            addCriterion("fpenging_income is not null");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeEqualTo(Long value) {
            addCriterion("fpenging_income =", value, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeNotEqualTo(Long value) {
            addCriterion("fpenging_income <>", value, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeGreaterThan(Long value) {
            addCriterion("fpenging_income >", value, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeGreaterThanOrEqualTo(Long value) {
            addCriterion("fpenging_income >=", value, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeLessThan(Long value) {
            addCriterion("fpenging_income <", value, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeLessThanOrEqualTo(Long value) {
            addCriterion("fpenging_income <=", value, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeIn(List<Long> values) {
            addCriterion("fpenging_income in", values, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeNotIn(List<Long> values) {
            addCriterion("fpenging_income not in", values, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeBetween(Long value1, Long value2) {
            addCriterion("fpenging_income between", value1, value2, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFpengingIncomeNotBetween(Long value1, Long value2) {
            addCriterion("fpenging_income not between", value1, value2, "fpengingIncome");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusIsNull() {
            addCriterion("fcredit_status is null");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusIsNotNull() {
            addCriterion("fcredit_status is not null");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusEqualTo(Boolean value) {
            addCriterion("fcredit_status =", value, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusNotEqualTo(Boolean value) {
            addCriterion("fcredit_status <>", value, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusGreaterThan(Boolean value) {
            addCriterion("fcredit_status >", value, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fcredit_status >=", value, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusLessThan(Boolean value) {
            addCriterion("fcredit_status <", value, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("fcredit_status <=", value, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusIn(List<Boolean> values) {
            addCriterion("fcredit_status in", values, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusNotIn(List<Boolean> values) {
            addCriterion("fcredit_status not in", values, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("fcredit_status between", value1, value2, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fcredit_status not between", value1, value2, "fcreditStatus");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeIsNull() {
            addCriterion("fcredit_recharge is null");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeIsNotNull() {
            addCriterion("fcredit_recharge is not null");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeEqualTo(Long value) {
            addCriterion("fcredit_recharge =", value, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeNotEqualTo(Long value) {
            addCriterion("fcredit_recharge <>", value, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeGreaterThan(Long value) {
            addCriterion("fcredit_recharge >", value, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeGreaterThanOrEqualTo(Long value) {
            addCriterion("fcredit_recharge >=", value, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeLessThan(Long value) {
            addCriterion("fcredit_recharge <", value, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeLessThanOrEqualTo(Long value) {
            addCriterion("fcredit_recharge <=", value, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeIn(List<Long> values) {
            addCriterion("fcredit_recharge in", values, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeNotIn(List<Long> values) {
            addCriterion("fcredit_recharge not in", values, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeBetween(Long value1, Long value2) {
            addCriterion("fcredit_recharge between", value1, value2, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditRechargeNotBetween(Long value1, Long value2) {
            addCriterion("fcredit_recharge not between", value1, value2, "fcreditRecharge");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceIsNull() {
            addCriterion("fcredit_balance is null");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceIsNotNull() {
            addCriterion("fcredit_balance is not null");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceEqualTo(Long value) {
            addCriterion("fcredit_balance =", value, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceNotEqualTo(Long value) {
            addCriterion("fcredit_balance <>", value, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceGreaterThan(Long value) {
            addCriterion("fcredit_balance >", value, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("fcredit_balance >=", value, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceLessThan(Long value) {
            addCriterion("fcredit_balance <", value, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceLessThanOrEqualTo(Long value) {
            addCriterion("fcredit_balance <=", value, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceIn(List<Long> values) {
            addCriterion("fcredit_balance in", values, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceNotIn(List<Long> values) {
            addCriterion("fcredit_balance not in", values, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceBetween(Long value1, Long value2) {
            addCriterion("fcredit_balance between", value1, value2, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditBalanceNotBetween(Long value1, Long value2) {
            addCriterion("fcredit_balance not between", value1, value2, "fcreditBalance");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountIsNull() {
            addCriterion("fcredit_pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountIsNotNull() {
            addCriterion("fcredit_pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountEqualTo(Long value) {
            addCriterion("fcredit_pay_amount =", value, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountNotEqualTo(Long value) {
            addCriterion("fcredit_pay_amount <>", value, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountGreaterThan(Long value) {
            addCriterion("fcredit_pay_amount >", value, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("fcredit_pay_amount >=", value, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountLessThan(Long value) {
            addCriterion("fcredit_pay_amount <", value, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountLessThanOrEqualTo(Long value) {
            addCriterion("fcredit_pay_amount <=", value, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountIn(List<Long> values) {
            addCriterion("fcredit_pay_amount in", values, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountNotIn(List<Long> values) {
            addCriterion("fcredit_pay_amount not in", values, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountBetween(Long value1, Long value2) {
            addCriterion("fcredit_pay_amount between", value1, value2, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFcreditPayAmountNotBetween(Long value1, Long value2) {
            addCriterion("fcredit_pay_amount not between", value1, value2, "fcreditPayAmount");
            return (Criteria) this;
        }

        public Criteria andFrechargeIsNull() {
            addCriterion("frecharge is null");
            return (Criteria) this;
        }

        public Criteria andFrechargeIsNotNull() {
            addCriterion("frecharge is not null");
            return (Criteria) this;
        }

        public Criteria andFrechargeEqualTo(Long value) {
            addCriterion("frecharge =", value, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeNotEqualTo(Long value) {
            addCriterion("frecharge <>", value, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeGreaterThan(Long value) {
            addCriterion("frecharge >", value, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeGreaterThanOrEqualTo(Long value) {
            addCriterion("frecharge >=", value, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeLessThan(Long value) {
            addCriterion("frecharge <", value, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeLessThanOrEqualTo(Long value) {
            addCriterion("frecharge <=", value, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeIn(List<Long> values) {
            addCriterion("frecharge in", values, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeNotIn(List<Long> values) {
            addCriterion("frecharge not in", values, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeBetween(Long value1, Long value2) {
            addCriterion("frecharge between", value1, value2, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFrechargeNotBetween(Long value1, Long value2) {
            addCriterion("frecharge not between", value1, value2, "frecharge");
            return (Criteria) this;
        }

        public Criteria andFwithdrawIsNull() {
            addCriterion("fwithdraw is null");
            return (Criteria) this;
        }

        public Criteria andFwithdrawIsNotNull() {
            addCriterion("fwithdraw is not null");
            return (Criteria) this;
        }

        public Criteria andFwithdrawEqualTo(Long value) {
            addCriterion("fwithdraw =", value, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawNotEqualTo(Long value) {
            addCriterion("fwithdraw <>", value, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawGreaterThan(Long value) {
            addCriterion("fwithdraw >", value, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawGreaterThanOrEqualTo(Long value) {
            addCriterion("fwithdraw >=", value, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawLessThan(Long value) {
            addCriterion("fwithdraw <", value, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawLessThanOrEqualTo(Long value) {
            addCriterion("fwithdraw <=", value, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawIn(List<Long> values) {
            addCriterion("fwithdraw in", values, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawNotIn(List<Long> values) {
            addCriterion("fwithdraw not in", values, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawBetween(Long value1, Long value2) {
            addCriterion("fwithdraw between", value1, value2, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFwithdrawNotBetween(Long value1, Long value2) {
            addCriterion("fwithdraw not between", value1, value2, "fwithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawIsNull() {
            addCriterion("ffreeze_withdraw is null");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawIsNotNull() {
            addCriterion("ffreeze_withdraw is not null");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawEqualTo(Long value) {
            addCriterion("ffreeze_withdraw =", value, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawNotEqualTo(Long value) {
            addCriterion("ffreeze_withdraw <>", value, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawGreaterThan(Long value) {
            addCriterion("ffreeze_withdraw >", value, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawGreaterThanOrEqualTo(Long value) {
            addCriterion("ffreeze_withdraw >=", value, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawLessThan(Long value) {
            addCriterion("ffreeze_withdraw <", value, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawLessThanOrEqualTo(Long value) {
            addCriterion("ffreeze_withdraw <=", value, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawIn(List<Long> values) {
            addCriterion("ffreeze_withdraw in", values, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawNotIn(List<Long> values) {
            addCriterion("ffreeze_withdraw not in", values, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawBetween(Long value1, Long value2) {
            addCriterion("ffreeze_withdraw between", value1, value2, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezeWithdrawNotBetween(Long value1, Long value2) {
            addCriterion("ffreeze_withdraw not between", value1, value2, "ffreezeWithdraw");
            return (Criteria) this;
        }

        public Criteria andFfreezePayIsNull() {
            addCriterion("ffreeze_pay is null");
            return (Criteria) this;
        }

        public Criteria andFfreezePayIsNotNull() {
            addCriterion("ffreeze_pay is not null");
            return (Criteria) this;
        }

        public Criteria andFfreezePayEqualTo(Long value) {
            addCriterion("ffreeze_pay =", value, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayNotEqualTo(Long value) {
            addCriterion("ffreeze_pay <>", value, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayGreaterThan(Long value) {
            addCriterion("ffreeze_pay >", value, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayGreaterThanOrEqualTo(Long value) {
            addCriterion("ffreeze_pay >=", value, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayLessThan(Long value) {
            addCriterion("ffreeze_pay <", value, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayLessThanOrEqualTo(Long value) {
            addCriterion("ffreeze_pay <=", value, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayIn(List<Long> values) {
            addCriterion("ffreeze_pay in", values, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayNotIn(List<Long> values) {
            addCriterion("ffreeze_pay not in", values, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayBetween(Long value1, Long value2) {
            addCriterion("ffreeze_pay between", value1, value2, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFfreezePayNotBetween(Long value1, Long value2) {
            addCriterion("ffreeze_pay not between", value1, value2, "ffreezePay");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkIsNull() {
            addCriterion("foperate_remark is null");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkIsNotNull() {
            addCriterion("foperate_remark is not null");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkEqualTo(String value) {
            addCriterion("foperate_remark =", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkNotEqualTo(String value) {
            addCriterion("foperate_remark <>", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkGreaterThan(String value) {
            addCriterion("foperate_remark >", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("foperate_remark >=", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkLessThan(String value) {
            addCriterion("foperate_remark <", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkLessThanOrEqualTo(String value) {
            addCriterion("foperate_remark <=", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkLike(String value) {
            addCriterion("foperate_remark like", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkNotLike(String value) {
            addCriterion("foperate_remark not like", value, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkIn(List<String> values) {
            addCriterion("foperate_remark in", values, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkNotIn(List<String> values) {
            addCriterion("foperate_remark not in", values, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkBetween(String value1, String value2) {
            addCriterion("foperate_remark between", value1, value2, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFoperateRemarkNotBetween(String value1, String value2) {
            addCriterion("foperate_remark not between", value1, value2, "foperateRemark");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIsNull() {
            addCriterion("fcreate_time is null");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIsNotNull() {
            addCriterion("fcreate_time is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeEqualTo(Date value) {
            addCriterion("fcreate_time =", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotEqualTo(Date value) {
            addCriterion("fcreate_time <>", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeGreaterThan(Date value) {
            addCriterion("fcreate_time >", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fcreate_time >=", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeLessThan(Date value) {
            addCriterion("fcreate_time <", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("fcreate_time <=", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIn(List<Date> values) {
            addCriterion("fcreate_time in", values, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotIn(List<Date> values) {
            addCriterion("fcreate_time not in", values, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeBetween(Date value1, Date value2) {
            addCriterion("fcreate_time between", value1, value2, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("fcreate_time not between", value1, value2, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIsNull() {
            addCriterion("fmodify_time is null");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIsNotNull() {
            addCriterion("fmodify_time is not null");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeEqualTo(Date value) {
            addCriterion("fmodify_time =", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotEqualTo(Date value) {
            addCriterion("fmodify_time <>", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeGreaterThan(Date value) {
            addCriterion("fmodify_time >", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fmodify_time >=", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeLessThan(Date value) {
            addCriterion("fmodify_time <", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("fmodify_time <=", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIn(List<Date> values) {
            addCriterion("fmodify_time in", values, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotIn(List<Date> values) {
            addCriterion("fmodify_time not in", values, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeBetween(Date value1, Date value2) {
            addCriterion("fmodify_time between", value1, value2, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("fmodify_time not between", value1, value2, "fmodifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_user_account
     *
     *   do_not_delete_during_merge Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_user_account
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}