package org.you.oops.order.domain.userorder.repository.po;

import java.util.Date;

public class BbcUserAccountPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fuid
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long fuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fbalance
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long fbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fpenging_income
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long fpengingIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fcredit_status
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Boolean fcreditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fcredit_recharge
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long fcreditRecharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fcredit_balance
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long fcreditBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fcredit_pay_amount
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long fcreditPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.frecharge
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long frecharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fwithdraw
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long fwithdraw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.ffreeze_withdraw
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long ffreezeWithdraw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.ffreeze_pay
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Long ffreezePay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.foperate_remark
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private String foperateRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fcreate_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Date fcreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user_account.fmodify_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Date fmodifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fuid
     *
     * @return the value of t_bbc_user_account.fuid
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFuid() {
        return fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fuid
     *
     * @param fuid the value for t_bbc_user_account.fuid
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFuid(Long fuid) {
        this.fuid = fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fbalance
     *
     * @return the value of t_bbc_user_account.fbalance
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFbalance() {
        return fbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fbalance
     *
     * @param fbalance the value for t_bbc_user_account.fbalance
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFbalance(Long fbalance) {
        this.fbalance = fbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fpenging_income
     *
     * @return the value of t_bbc_user_account.fpenging_income
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFpengingIncome() {
        return fpengingIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fpenging_income
     *
     * @param fpengingIncome the value for t_bbc_user_account.fpenging_income
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFpengingIncome(Long fpengingIncome) {
        this.fpengingIncome = fpengingIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fcredit_status
     *
     * @return the value of t_bbc_user_account.fcredit_status
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Boolean getFcreditStatus() {
        return fcreditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fcredit_status
     *
     * @param fcreditStatus the value for t_bbc_user_account.fcredit_status
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFcreditStatus(Boolean fcreditStatus) {
        this.fcreditStatus = fcreditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fcredit_recharge
     *
     * @return the value of t_bbc_user_account.fcredit_recharge
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFcreditRecharge() {
        return fcreditRecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fcredit_recharge
     *
     * @param fcreditRecharge the value for t_bbc_user_account.fcredit_recharge
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFcreditRecharge(Long fcreditRecharge) {
        this.fcreditRecharge = fcreditRecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fcredit_balance
     *
     * @return the value of t_bbc_user_account.fcredit_balance
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFcreditBalance() {
        return fcreditBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fcredit_balance
     *
     * @param fcreditBalance the value for t_bbc_user_account.fcredit_balance
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFcreditBalance(Long fcreditBalance) {
        this.fcreditBalance = fcreditBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fcredit_pay_amount
     *
     * @return the value of t_bbc_user_account.fcredit_pay_amount
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFcreditPayAmount() {
        return fcreditPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fcredit_pay_amount
     *
     * @param fcreditPayAmount the value for t_bbc_user_account.fcredit_pay_amount
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFcreditPayAmount(Long fcreditPayAmount) {
        this.fcreditPayAmount = fcreditPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.frecharge
     *
     * @return the value of t_bbc_user_account.frecharge
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFrecharge() {
        return frecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.frecharge
     *
     * @param frecharge the value for t_bbc_user_account.frecharge
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFrecharge(Long frecharge) {
        this.frecharge = frecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fwithdraw
     *
     * @return the value of t_bbc_user_account.fwithdraw
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFwithdraw() {
        return fwithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fwithdraw
     *
     * @param fwithdraw the value for t_bbc_user_account.fwithdraw
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFwithdraw(Long fwithdraw) {
        this.fwithdraw = fwithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.ffreeze_withdraw
     *
     * @return the value of t_bbc_user_account.ffreeze_withdraw
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFfreezeWithdraw() {
        return ffreezeWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.ffreeze_withdraw
     *
     * @param ffreezeWithdraw the value for t_bbc_user_account.ffreeze_withdraw
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFfreezeWithdraw(Long ffreezeWithdraw) {
        this.ffreezeWithdraw = ffreezeWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.ffreeze_pay
     *
     * @return the value of t_bbc_user_account.ffreeze_pay
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Long getFfreezePay() {
        return ffreezePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.ffreeze_pay
     *
     * @param ffreezePay the value for t_bbc_user_account.ffreeze_pay
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFfreezePay(Long ffreezePay) {
        this.ffreezePay = ffreezePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.foperate_remark
     *
     * @return the value of t_bbc_user_account.foperate_remark
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public String getFoperateRemark() {
        return foperateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.foperate_remark
     *
     * @param foperateRemark the value for t_bbc_user_account.foperate_remark
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFoperateRemark(String foperateRemark) {
        this.foperateRemark = foperateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fcreate_time
     *
     * @return the value of t_bbc_user_account.fcreate_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Date getFcreateTime() {
        return fcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fcreate_time
     *
     * @param fcreateTime the value for t_bbc_user_account.fcreate_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFcreateTime(Date fcreateTime) {
        this.fcreateTime = fcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user_account.fmodify_time
     *
     * @return the value of t_bbc_user_account.fmodify_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Date getFmodifyTime() {
        return fmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user_account.fmodify_time
     *
     * @param fmodifyTime the value for t_bbc_user_account.fmodify_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFmodifyTime(Date fmodifyTime) {
        this.fmodifyTime = fmodifyTime;
    }
}