package org.you.oops.order.domain.userorder.repository.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BbcUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public BbcUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFuidIsNull() {
            addCriterion("fuid is null");
            return (Criteria) this;
        }

        public Criteria andFuidIsNotNull() {
            addCriterion("fuid is not null");
            return (Criteria) this;
        }

        public Criteria andFuidEqualTo(Long value) {
            addCriterion("fuid =", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidNotEqualTo(Long value) {
            addCriterion("fuid <>", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidGreaterThan(Long value) {
            addCriterion("fuid >", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidGreaterThanOrEqualTo(Long value) {
            addCriterion("fuid >=", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidLessThan(Long value) {
            addCriterion("fuid <", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidLessThanOrEqualTo(Long value) {
            addCriterion("fuid <=", value, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidIn(List<Long> values) {
            addCriterion("fuid in", values, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidNotIn(List<Long> values) {
            addCriterion("fuid not in", values, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidBetween(Long value1, Long value2) {
            addCriterion("fuid between", value1, value2, "fuid");
            return (Criteria) this;
        }

        public Criteria andFuidNotBetween(Long value1, Long value2) {
            addCriterion("fuid not between", value1, value2, "fuid");
            return (Criteria) this;
        }

        public Criteria andFunameIsNull() {
            addCriterion("funame is null");
            return (Criteria) this;
        }

        public Criteria andFunameIsNotNull() {
            addCriterion("funame is not null");
            return (Criteria) this;
        }

        public Criteria andFunameEqualTo(String value) {
            addCriterion("funame =", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameNotEqualTo(String value) {
            addCriterion("funame <>", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameGreaterThan(String value) {
            addCriterion("funame >", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameGreaterThanOrEqualTo(String value) {
            addCriterion("funame >=", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameLessThan(String value) {
            addCriterion("funame <", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameLessThanOrEqualTo(String value) {
            addCriterion("funame <=", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameLike(String value) {
            addCriterion("funame like", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameNotLike(String value) {
            addCriterion("funame not like", value, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameIn(List<String> values) {
            addCriterion("funame in", values, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameNotIn(List<String> values) {
            addCriterion("funame not in", values, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameBetween(String value1, String value2) {
            addCriterion("funame between", value1, value2, "funame");
            return (Criteria) this;
        }

        public Criteria andFunameNotBetween(String value1, String value2) {
            addCriterion("funame not between", value1, value2, "funame");
            return (Criteria) this;
        }

        public Criteria andFnicknameIsNull() {
            addCriterion("fnickname is null");
            return (Criteria) this;
        }

        public Criteria andFnicknameIsNotNull() {
            addCriterion("fnickname is not null");
            return (Criteria) this;
        }

        public Criteria andFnicknameEqualTo(String value) {
            addCriterion("fnickname =", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameNotEqualTo(String value) {
            addCriterion("fnickname <>", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameGreaterThan(String value) {
            addCriterion("fnickname >", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameGreaterThanOrEqualTo(String value) {
            addCriterion("fnickname >=", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameLessThan(String value) {
            addCriterion("fnickname <", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameLessThanOrEqualTo(String value) {
            addCriterion("fnickname <=", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameLike(String value) {
            addCriterion("fnickname like", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameNotLike(String value) {
            addCriterion("fnickname not like", value, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameIn(List<String> values) {
            addCriterion("fnickname in", values, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameNotIn(List<String> values) {
            addCriterion("fnickname not in", values, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameBetween(String value1, String value2) {
            addCriterion("fnickname between", value1, value2, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFnicknameNotBetween(String value1, String value2) {
            addCriterion("fnickname not between", value1, value2, "fnickname");
            return (Criteria) this;
        }

        public Criteria andFheadpicIsNull() {
            addCriterion("fheadpic is null");
            return (Criteria) this;
        }

        public Criteria andFheadpicIsNotNull() {
            addCriterion("fheadpic is not null");
            return (Criteria) this;
        }

        public Criteria andFheadpicEqualTo(String value) {
            addCriterion("fheadpic =", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicNotEqualTo(String value) {
            addCriterion("fheadpic <>", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicGreaterThan(String value) {
            addCriterion("fheadpic >", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicGreaterThanOrEqualTo(String value) {
            addCriterion("fheadpic >=", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicLessThan(String value) {
            addCriterion("fheadpic <", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicLessThanOrEqualTo(String value) {
            addCriterion("fheadpic <=", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicLike(String value) {
            addCriterion("fheadpic like", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicNotLike(String value) {
            addCriterion("fheadpic not like", value, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicIn(List<String> values) {
            addCriterion("fheadpic in", values, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicNotIn(List<String> values) {
            addCriterion("fheadpic not in", values, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicBetween(String value1, String value2) {
            addCriterion("fheadpic between", value1, value2, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFheadpicNotBetween(String value1, String value2) {
            addCriterion("fheadpic not between", value1, value2, "fheadpic");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdIsNull() {
            addCriterion("fuser_level_id is null");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdIsNotNull() {
            addCriterion("fuser_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdEqualTo(Long value) {
            addCriterion("fuser_level_id =", value, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdNotEqualTo(Long value) {
            addCriterion("fuser_level_id <>", value, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdGreaterThan(Long value) {
            addCriterion("fuser_level_id >", value, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("fuser_level_id >=", value, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdLessThan(Long value) {
            addCriterion("fuser_level_id <", value, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdLessThanOrEqualTo(Long value) {
            addCriterion("fuser_level_id <=", value, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdIn(List<Long> values) {
            addCriterion("fuser_level_id in", values, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdNotIn(List<Long> values) {
            addCriterion("fuser_level_id not in", values, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdBetween(Long value1, Long value2) {
            addCriterion("fuser_level_id between", value1, value2, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFuserLevelIdNotBetween(Long value1, Long value2) {
            addCriterion("fuser_level_id not between", value1, value2, "fuserLevelId");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeIsNull() {
            addCriterion("foperate_type is null");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeIsNotNull() {
            addCriterion("foperate_type is not null");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeEqualTo(Boolean value) {
            addCriterion("foperate_type =", value, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeNotEqualTo(Boolean value) {
            addCriterion("foperate_type <>", value, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeGreaterThan(Boolean value) {
            addCriterion("foperate_type >", value, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("foperate_type >=", value, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeLessThan(Boolean value) {
            addCriterion("foperate_type <", value, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("foperate_type <=", value, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeIn(List<Boolean> values) {
            addCriterion("foperate_type in", values, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeNotIn(List<Boolean> values) {
            addCriterion("foperate_type not in", values, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("foperate_type between", value1, value2, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFoperateTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("foperate_type not between", value1, value2, "foperateType");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdIsNull() {
            addCriterion("fmarket_bd_id is null");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdIsNotNull() {
            addCriterion("fmarket_bd_id is not null");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdEqualTo(Long value) {
            addCriterion("fmarket_bd_id =", value, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdNotEqualTo(Long value) {
            addCriterion("fmarket_bd_id <>", value, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdGreaterThan(Long value) {
            addCriterion("fmarket_bd_id >", value, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdGreaterThanOrEqualTo(Long value) {
            addCriterion("fmarket_bd_id >=", value, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdLessThan(Long value) {
            addCriterion("fmarket_bd_id <", value, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdLessThanOrEqualTo(Long value) {
            addCriterion("fmarket_bd_id <=", value, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdIn(List<Long> values) {
            addCriterion("fmarket_bd_id in", values, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdNotIn(List<Long> values) {
            addCriterion("fmarket_bd_id not in", values, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdBetween(Long value1, Long value2) {
            addCriterion("fmarket_bd_id between", value1, value2, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFmarketBdIdNotBetween(Long value1, Long value2) {
            addCriterion("fmarket_bd_id not between", value1, value2, "fmarketBdId");
            return (Criteria) this;
        }

        public Criteria andFpasswdIsNull() {
            addCriterion("fpasswd is null");
            return (Criteria) this;
        }

        public Criteria andFpasswdIsNotNull() {
            addCriterion("fpasswd is not null");
            return (Criteria) this;
        }

        public Criteria andFpasswdEqualTo(String value) {
            addCriterion("fpasswd =", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdNotEqualTo(String value) {
            addCriterion("fpasswd <>", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdGreaterThan(String value) {
            addCriterion("fpasswd >", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdGreaterThanOrEqualTo(String value) {
            addCriterion("fpasswd >=", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdLessThan(String value) {
            addCriterion("fpasswd <", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdLessThanOrEqualTo(String value) {
            addCriterion("fpasswd <=", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdLike(String value) {
            addCriterion("fpasswd like", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdNotLike(String value) {
            addCriterion("fpasswd not like", value, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdIn(List<String> values) {
            addCriterion("fpasswd in", values, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdNotIn(List<String> values) {
            addCriterion("fpasswd not in", values, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdBetween(String value1, String value2) {
            addCriterion("fpasswd between", value1, value2, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFpasswdNotBetween(String value1, String value2) {
            addCriterion("fpasswd not between", value1, value2, "fpasswd");
            return (Criteria) this;
        }

        public Criteria andFsexIsNull() {
            addCriterion("fsex is null");
            return (Criteria) this;
        }

        public Criteria andFsexIsNotNull() {
            addCriterion("fsex is not null");
            return (Criteria) this;
        }

        public Criteria andFsexEqualTo(Boolean value) {
            addCriterion("fsex =", value, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexNotEqualTo(Boolean value) {
            addCriterion("fsex <>", value, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexGreaterThan(Boolean value) {
            addCriterion("fsex >", value, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fsex >=", value, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexLessThan(Boolean value) {
            addCriterion("fsex <", value, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexLessThanOrEqualTo(Boolean value) {
            addCriterion("fsex <=", value, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexIn(List<Boolean> values) {
            addCriterion("fsex in", values, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexNotIn(List<Boolean> values) {
            addCriterion("fsex not in", values, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexBetween(Boolean value1, Boolean value2) {
            addCriterion("fsex between", value1, value2, "fsex");
            return (Criteria) this;
        }

        public Criteria andFsexNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fsex not between", value1, value2, "fsex");
            return (Criteria) this;
        }

        public Criteria andFbirthdayIsNull() {
            addCriterion("fbirthday is null");
            return (Criteria) this;
        }

        public Criteria andFbirthdayIsNotNull() {
            addCriterion("fbirthday is not null");
            return (Criteria) this;
        }

        public Criteria andFbirthdayEqualTo(Date value) {
            addCriterion("fbirthday =", value, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayNotEqualTo(Date value) {
            addCriterion("fbirthday <>", value, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayGreaterThan(Date value) {
            addCriterion("fbirthday >", value, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("fbirthday >=", value, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayLessThan(Date value) {
            addCriterion("fbirthday <", value, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayLessThanOrEqualTo(Date value) {
            addCriterion("fbirthday <=", value, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayIn(List<Date> values) {
            addCriterion("fbirthday in", values, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayNotIn(List<Date> values) {
            addCriterion("fbirthday not in", values, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayBetween(Date value1, Date value2) {
            addCriterion("fbirthday between", value1, value2, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFbirthdayNotBetween(Date value1, Date value2) {
            addCriterion("fbirthday not between", value1, value2, "fbirthday");
            return (Criteria) this;
        }

        public Criteria andFtelephoneIsNull() {
            addCriterion("ftelephone is null");
            return (Criteria) this;
        }

        public Criteria andFtelephoneIsNotNull() {
            addCriterion("ftelephone is not null");
            return (Criteria) this;
        }

        public Criteria andFtelephoneEqualTo(String value) {
            addCriterion("ftelephone =", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneNotEqualTo(String value) {
            addCriterion("ftelephone <>", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneGreaterThan(String value) {
            addCriterion("ftelephone >", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("ftelephone >=", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneLessThan(String value) {
            addCriterion("ftelephone <", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneLessThanOrEqualTo(String value) {
            addCriterion("ftelephone <=", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneLike(String value) {
            addCriterion("ftelephone like", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneNotLike(String value) {
            addCriterion("ftelephone not like", value, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneIn(List<String> values) {
            addCriterion("ftelephone in", values, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneNotIn(List<String> values) {
            addCriterion("ftelephone not in", values, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneBetween(String value1, String value2) {
            addCriterion("ftelephone between", value1, value2, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFtelephoneNotBetween(String value1, String value2) {
            addCriterion("ftelephone not between", value1, value2, "ftelephone");
            return (Criteria) this;
        }

        public Criteria andFmobileIsNull() {
            addCriterion("fmobile is null");
            return (Criteria) this;
        }

        public Criteria andFmobileIsNotNull() {
            addCriterion("fmobile is not null");
            return (Criteria) this;
        }

        public Criteria andFmobileEqualTo(String value) {
            addCriterion("fmobile =", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileNotEqualTo(String value) {
            addCriterion("fmobile <>", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileGreaterThan(String value) {
            addCriterion("fmobile >", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileGreaterThanOrEqualTo(String value) {
            addCriterion("fmobile >=", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileLessThan(String value) {
            addCriterion("fmobile <", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileLessThanOrEqualTo(String value) {
            addCriterion("fmobile <=", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileLike(String value) {
            addCriterion("fmobile like", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileNotLike(String value) {
            addCriterion("fmobile not like", value, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileIn(List<String> values) {
            addCriterion("fmobile in", values, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileNotIn(List<String> values) {
            addCriterion("fmobile not in", values, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileBetween(String value1, String value2) {
            addCriterion("fmobile between", value1, value2, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmobileNotBetween(String value1, String value2) {
            addCriterion("fmobile not between", value1, value2, "fmobile");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidIsNull() {
            addCriterion("fmoblie_is_valid is null");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidIsNotNull() {
            addCriterion("fmoblie_is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidEqualTo(Boolean value) {
            addCriterion("fmoblie_is_valid =", value, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidNotEqualTo(Boolean value) {
            addCriterion("fmoblie_is_valid <>", value, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidGreaterThan(Boolean value) {
            addCriterion("fmoblie_is_valid >", value, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fmoblie_is_valid >=", value, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidLessThan(Boolean value) {
            addCriterion("fmoblie_is_valid <", value, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidLessThanOrEqualTo(Boolean value) {
            addCriterion("fmoblie_is_valid <=", value, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidIn(List<Boolean> values) {
            addCriterion("fmoblie_is_valid in", values, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidNotIn(List<Boolean> values) {
            addCriterion("fmoblie_is_valid not in", values, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidBetween(Boolean value1, Boolean value2) {
            addCriterion("fmoblie_is_valid between", value1, value2, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmoblieIsValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fmoblie_is_valid not between", value1, value2, "fmoblieIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsNull() {
            addCriterion("fmail is null");
            return (Criteria) this;
        }

        public Criteria andFmailIsNotNull() {
            addCriterion("fmail is not null");
            return (Criteria) this;
        }

        public Criteria andFmailEqualTo(String value) {
            addCriterion("fmail =", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailNotEqualTo(String value) {
            addCriterion("fmail <>", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailGreaterThan(String value) {
            addCriterion("fmail >", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailGreaterThanOrEqualTo(String value) {
            addCriterion("fmail >=", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailLessThan(String value) {
            addCriterion("fmail <", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailLessThanOrEqualTo(String value) {
            addCriterion("fmail <=", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailLike(String value) {
            addCriterion("fmail like", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailNotLike(String value) {
            addCriterion("fmail not like", value, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailIn(List<String> values) {
            addCriterion("fmail in", values, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailNotIn(List<String> values) {
            addCriterion("fmail not in", values, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailBetween(String value1, String value2) {
            addCriterion("fmail between", value1, value2, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailNotBetween(String value1, String value2) {
            addCriterion("fmail not between", value1, value2, "fmail");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidIsNull() {
            addCriterion("fmail_is_valid is null");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidIsNotNull() {
            addCriterion("fmail_is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidEqualTo(Boolean value) {
            addCriterion("fmail_is_valid =", value, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidNotEqualTo(Boolean value) {
            addCriterion("fmail_is_valid <>", value, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidGreaterThan(Boolean value) {
            addCriterion("fmail_is_valid >", value, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fmail_is_valid >=", value, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidLessThan(Boolean value) {
            addCriterion("fmail_is_valid <", value, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidLessThanOrEqualTo(Boolean value) {
            addCriterion("fmail_is_valid <=", value, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidIn(List<Boolean> values) {
            addCriterion("fmail_is_valid in", values, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidNotIn(List<Boolean> values) {
            addCriterion("fmail_is_valid not in", values, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidBetween(Boolean value1, Boolean value2) {
            addCriterion("fmail_is_valid between", value1, value2, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFmailIsValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fmail_is_valid not between", value1, value2, "fmailIsValid");
            return (Criteria) this;
        }

        public Criteria andFqqNoIsNull() {
            addCriterion("fqq_no is null");
            return (Criteria) this;
        }

        public Criteria andFqqNoIsNotNull() {
            addCriterion("fqq_no is not null");
            return (Criteria) this;
        }

        public Criteria andFqqNoEqualTo(String value) {
            addCriterion("fqq_no =", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoNotEqualTo(String value) {
            addCriterion("fqq_no <>", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoGreaterThan(String value) {
            addCriterion("fqq_no >", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoGreaterThanOrEqualTo(String value) {
            addCriterion("fqq_no >=", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoLessThan(String value) {
            addCriterion("fqq_no <", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoLessThanOrEqualTo(String value) {
            addCriterion("fqq_no <=", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoLike(String value) {
            addCriterion("fqq_no like", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoNotLike(String value) {
            addCriterion("fqq_no not like", value, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoIn(List<String> values) {
            addCriterion("fqq_no in", values, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoNotIn(List<String> values) {
            addCriterion("fqq_no not in", values, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoBetween(String value1, String value2) {
            addCriterion("fqq_no between", value1, value2, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFqqNoNotBetween(String value1, String value2) {
            addCriterion("fqq_no not between", value1, value2, "fqqNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoIsNull() {
            addCriterion("fwechat_no is null");
            return (Criteria) this;
        }

        public Criteria andFwechatNoIsNotNull() {
            addCriterion("fwechat_no is not null");
            return (Criteria) this;
        }

        public Criteria andFwechatNoEqualTo(String value) {
            addCriterion("fwechat_no =", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoNotEqualTo(String value) {
            addCriterion("fwechat_no <>", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoGreaterThan(String value) {
            addCriterion("fwechat_no >", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoGreaterThanOrEqualTo(String value) {
            addCriterion("fwechat_no >=", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoLessThan(String value) {
            addCriterion("fwechat_no <", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoLessThanOrEqualTo(String value) {
            addCriterion("fwechat_no <=", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoLike(String value) {
            addCriterion("fwechat_no like", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoNotLike(String value) {
            addCriterion("fwechat_no not like", value, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoIn(List<String> values) {
            addCriterion("fwechat_no in", values, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoNotIn(List<String> values) {
            addCriterion("fwechat_no not in", values, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoBetween(String value1, String value2) {
            addCriterion("fwechat_no between", value1, value2, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwechatNoNotBetween(String value1, String value2) {
            addCriterion("fwechat_no not between", value1, value2, "fwechatNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoIsNull() {
            addCriterion("fwangwang_no is null");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoIsNotNull() {
            addCriterion("fwangwang_no is not null");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoEqualTo(String value) {
            addCriterion("fwangwang_no =", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoNotEqualTo(String value) {
            addCriterion("fwangwang_no <>", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoGreaterThan(String value) {
            addCriterion("fwangwang_no >", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoGreaterThanOrEqualTo(String value) {
            addCriterion("fwangwang_no >=", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoLessThan(String value) {
            addCriterion("fwangwang_no <", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoLessThanOrEqualTo(String value) {
            addCriterion("fwangwang_no <=", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoLike(String value) {
            addCriterion("fwangwang_no like", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoNotLike(String value) {
            addCriterion("fwangwang_no not like", value, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoIn(List<String> values) {
            addCriterion("fwangwang_no in", values, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoNotIn(List<String> values) {
            addCriterion("fwangwang_no not in", values, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoBetween(String value1, String value2) {
            addCriterion("fwangwang_no between", value1, value2, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwangwangNoNotBetween(String value1, String value2) {
            addCriterion("fwangwang_no not between", value1, value2, "fwangwangNo");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdIsNull() {
            addCriterion("fwithdraw_passwd is null");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdIsNotNull() {
            addCriterion("fwithdraw_passwd is not null");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdEqualTo(String value) {
            addCriterion("fwithdraw_passwd =", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdNotEqualTo(String value) {
            addCriterion("fwithdraw_passwd <>", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdGreaterThan(String value) {
            addCriterion("fwithdraw_passwd >", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("fwithdraw_passwd >=", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdLessThan(String value) {
            addCriterion("fwithdraw_passwd <", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdLessThanOrEqualTo(String value) {
            addCriterion("fwithdraw_passwd <=", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdLike(String value) {
            addCriterion("fwithdraw_passwd like", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdNotLike(String value) {
            addCriterion("fwithdraw_passwd not like", value, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdIn(List<String> values) {
            addCriterion("fwithdraw_passwd in", values, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdNotIn(List<String> values) {
            addCriterion("fwithdraw_passwd not in", values, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdBetween(String value1, String value2) {
            addCriterion("fwithdraw_passwd between", value1, value2, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFwithdrawPasswdNotBetween(String value1, String value2) {
            addCriterion("fwithdraw_passwd not between", value1, value2, "fwithdrawPasswd");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusIsNull() {
            addCriterion("ffreeze_status is null");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusIsNotNull() {
            addCriterion("ffreeze_status is not null");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusEqualTo(Boolean value) {
            addCriterion("ffreeze_status =", value, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusNotEqualTo(Boolean value) {
            addCriterion("ffreeze_status <>", value, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusGreaterThan(Boolean value) {
            addCriterion("ffreeze_status >", value, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ffreeze_status >=", value, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusLessThan(Boolean value) {
            addCriterion("ffreeze_status <", value, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("ffreeze_status <=", value, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusIn(List<Boolean> values) {
            addCriterion("ffreeze_status in", values, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusNotIn(List<Boolean> values) {
            addCriterion("ffreeze_status not in", values, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("ffreeze_status between", value1, value2, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFfreezeStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ffreeze_status not between", value1, value2, "ffreezeStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusIsNull() {
            addCriterion("fverify_status is null");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusIsNotNull() {
            addCriterion("fverify_status is not null");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusEqualTo(Boolean value) {
            addCriterion("fverify_status =", value, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusNotEqualTo(Boolean value) {
            addCriterion("fverify_status <>", value, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusGreaterThan(Boolean value) {
            addCriterion("fverify_status >", value, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fverify_status >=", value, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusLessThan(Boolean value) {
            addCriterion("fverify_status <", value, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("fverify_status <=", value, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusIn(List<Boolean> values) {
            addCriterion("fverify_status in", values, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusNotIn(List<Boolean> values) {
            addCriterion("fverify_status not in", values, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("fverify_status between", value1, value2, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFverifyStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fverify_status not between", value1, value2, "fverifyStatus");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeIsNull() {
            addCriterion("fuser_valid_time is null");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeIsNotNull() {
            addCriterion("fuser_valid_time is not null");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeEqualTo(Date value) {
            addCriterion("fuser_valid_time =", value, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeNotEqualTo(Date value) {
            addCriterion("fuser_valid_time <>", value, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeGreaterThan(Date value) {
            addCriterion("fuser_valid_time >", value, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fuser_valid_time >=", value, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeLessThan(Date value) {
            addCriterion("fuser_valid_time <", value, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeLessThanOrEqualTo(Date value) {
            addCriterion("fuser_valid_time <=", value, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeIn(List<Date> values) {
            addCriterion("fuser_valid_time in", values, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeNotIn(List<Date> values) {
            addCriterion("fuser_valid_time not in", values, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeBetween(Date value1, Date value2) {
            addCriterion("fuser_valid_time between", value1, value2, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFuserValidTimeNotBetween(Date value1, Date value2) {
            addCriterion("fuser_valid_time not between", value1, value2, "fuserValidTime");
            return (Criteria) this;
        }

        public Criteria andFinviterIsNull() {
            addCriterion("finviter is null");
            return (Criteria) this;
        }

        public Criteria andFinviterIsNotNull() {
            addCriterion("finviter is not null");
            return (Criteria) this;
        }

        public Criteria andFinviterEqualTo(String value) {
            addCriterion("finviter =", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterNotEqualTo(String value) {
            addCriterion("finviter <>", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterGreaterThan(String value) {
            addCriterion("finviter >", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterGreaterThanOrEqualTo(String value) {
            addCriterion("finviter >=", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterLessThan(String value) {
            addCriterion("finviter <", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterLessThanOrEqualTo(String value) {
            addCriterion("finviter <=", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterLike(String value) {
            addCriterion("finviter like", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterNotLike(String value) {
            addCriterion("finviter not like", value, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterIn(List<String> values) {
            addCriterion("finviter in", values, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterNotIn(List<String> values) {
            addCriterion("finviter not in", values, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterBetween(String value1, String value2) {
            addCriterion("finviter between", value1, value2, "finviter");
            return (Criteria) this;
        }

        public Criteria andFinviterNotBetween(String value1, String value2) {
            addCriterion("finviter not between", value1, value2, "finviter");
            return (Criteria) this;
        }

        public Criteria andFregisterFromIsNull() {
            addCriterion("fregister_from is null");
            return (Criteria) this;
        }

        public Criteria andFregisterFromIsNotNull() {
            addCriterion("fregister_from is not null");
            return (Criteria) this;
        }

        public Criteria andFregisterFromEqualTo(String value) {
            addCriterion("fregister_from =", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromNotEqualTo(String value) {
            addCriterion("fregister_from <>", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromGreaterThan(String value) {
            addCriterion("fregister_from >", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromGreaterThanOrEqualTo(String value) {
            addCriterion("fregister_from >=", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromLessThan(String value) {
            addCriterion("fregister_from <", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromLessThanOrEqualTo(String value) {
            addCriterion("fregister_from <=", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromLike(String value) {
            addCriterion("fregister_from like", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromNotLike(String value) {
            addCriterion("fregister_from not like", value, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromIn(List<String> values) {
            addCriterion("fregister_from in", values, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromNotIn(List<String> values) {
            addCriterion("fregister_from not in", values, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromBetween(String value1, String value2) {
            addCriterion("fregister_from between", value1, value2, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFregisterFromNotBetween(String value1, String value2) {
            addCriterion("fregister_from not between", value1, value2, "fregisterFrom");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeIsNull() {
            addCriterion("fchannel_type is null");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeIsNotNull() {
            addCriterion("fchannel_type is not null");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeEqualTo(Boolean value) {
            addCriterion("fchannel_type =", value, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeNotEqualTo(Boolean value) {
            addCriterion("fchannel_type <>", value, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeGreaterThan(Boolean value) {
            addCriterion("fchannel_type >", value, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fchannel_type >=", value, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeLessThan(Boolean value) {
            addCriterion("fchannel_type <", value, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("fchannel_type <=", value, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeIn(List<Boolean> values) {
            addCriterion("fchannel_type in", values, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeNotIn(List<Boolean> values) {
            addCriterion("fchannel_type not in", values, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("fchannel_type between", value1, value2, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFchannelTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fchannel_type not between", value1, value2, "fchannelType");
            return (Criteria) this;
        }

        public Criteria andFisDeleteIsNull() {
            addCriterion("fis_delete is null");
            return (Criteria) this;
        }

        public Criteria andFisDeleteIsNotNull() {
            addCriterion("fis_delete is not null");
            return (Criteria) this;
        }

        public Criteria andFisDeleteEqualTo(Boolean value) {
            addCriterion("fis_delete =", value, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteNotEqualTo(Boolean value) {
            addCriterion("fis_delete <>", value, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteGreaterThan(Boolean value) {
            addCriterion("fis_delete >", value, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fis_delete >=", value, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteLessThan(Boolean value) {
            addCriterion("fis_delete <", value, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("fis_delete <=", value, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteIn(List<Boolean> values) {
            addCriterion("fis_delete in", values, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteNotIn(List<Boolean> values) {
            addCriterion("fis_delete not in", values, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("fis_delete between", value1, value2, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFisDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fis_delete not between", value1, value2, "fisDelete");
            return (Criteria) this;
        }

        public Criteria andFremarkIsNull() {
            addCriterion("fremark is null");
            return (Criteria) this;
        }

        public Criteria andFremarkIsNotNull() {
            addCriterion("fremark is not null");
            return (Criteria) this;
        }

        public Criteria andFremarkEqualTo(String value) {
            addCriterion("fremark =", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkNotEqualTo(String value) {
            addCriterion("fremark <>", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkGreaterThan(String value) {
            addCriterion("fremark >", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkGreaterThanOrEqualTo(String value) {
            addCriterion("fremark >=", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkLessThan(String value) {
            addCriterion("fremark <", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkLessThanOrEqualTo(String value) {
            addCriterion("fremark <=", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkLike(String value) {
            addCriterion("fremark like", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkNotLike(String value) {
            addCriterion("fremark not like", value, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkIn(List<String> values) {
            addCriterion("fremark in", values, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkNotIn(List<String> values) {
            addCriterion("fremark not in", values, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkBetween(String value1, String value2) {
            addCriterion("fremark between", value1, value2, "fremark");
            return (Criteria) this;
        }

        public Criteria andFremarkNotBetween(String value1, String value2) {
            addCriterion("fremark not between", value1, value2, "fremark");
            return (Criteria) this;
        }

        public Criteria andFidcardNoIsNull() {
            addCriterion("fidcard_no is null");
            return (Criteria) this;
        }

        public Criteria andFidcardNoIsNotNull() {
            addCriterion("fidcard_no is not null");
            return (Criteria) this;
        }

        public Criteria andFidcardNoEqualTo(String value) {
            addCriterion("fidcard_no =", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoNotEqualTo(String value) {
            addCriterion("fidcard_no <>", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoGreaterThan(String value) {
            addCriterion("fidcard_no >", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoGreaterThanOrEqualTo(String value) {
            addCriterion("fidcard_no >=", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoLessThan(String value) {
            addCriterion("fidcard_no <", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoLessThanOrEqualTo(String value) {
            addCriterion("fidcard_no <=", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoLike(String value) {
            addCriterion("fidcard_no like", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoNotLike(String value) {
            addCriterion("fidcard_no not like", value, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoIn(List<String> values) {
            addCriterion("fidcard_no in", values, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoNotIn(List<String> values) {
            addCriterion("fidcard_no not in", values, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoBetween(String value1, String value2) {
            addCriterion("fidcard_no between", value1, value2, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNoNotBetween(String value1, String value2) {
            addCriterion("fidcard_no not between", value1, value2, "fidcardNo");
            return (Criteria) this;
        }

        public Criteria andFidcardNameIsNull() {
            addCriterion("fidcard_name is null");
            return (Criteria) this;
        }

        public Criteria andFidcardNameIsNotNull() {
            addCriterion("fidcard_name is not null");
            return (Criteria) this;
        }

        public Criteria andFidcardNameEqualTo(String value) {
            addCriterion("fidcard_name =", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameNotEqualTo(String value) {
            addCriterion("fidcard_name <>", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameGreaterThan(String value) {
            addCriterion("fidcard_name >", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameGreaterThanOrEqualTo(String value) {
            addCriterion("fidcard_name >=", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameLessThan(String value) {
            addCriterion("fidcard_name <", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameLessThanOrEqualTo(String value) {
            addCriterion("fidcard_name <=", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameLike(String value) {
            addCriterion("fidcard_name like", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameNotLike(String value) {
            addCriterion("fidcard_name not like", value, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameIn(List<String> values) {
            addCriterion("fidcard_name in", values, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameNotIn(List<String> values) {
            addCriterion("fidcard_name not in", values, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameBetween(String value1, String value2) {
            addCriterion("fidcard_name between", value1, value2, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFidcardNameNotBetween(String value1, String value2) {
            addCriterion("fidcard_name not between", value1, value2, "fidcardName");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeIsNull() {
            addCriterion("fmobile_valid_time is null");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeIsNotNull() {
            addCriterion("fmobile_valid_time is not null");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeEqualTo(Date value) {
            addCriterion("fmobile_valid_time =", value, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeNotEqualTo(Date value) {
            addCriterion("fmobile_valid_time <>", value, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeGreaterThan(Date value) {
            addCriterion("fmobile_valid_time >", value, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fmobile_valid_time >=", value, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeLessThan(Date value) {
            addCriterion("fmobile_valid_time <", value, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeLessThanOrEqualTo(Date value) {
            addCriterion("fmobile_valid_time <=", value, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeIn(List<Date> values) {
            addCriterion("fmobile_valid_time in", values, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeNotIn(List<Date> values) {
            addCriterion("fmobile_valid_time not in", values, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeBetween(Date value1, Date value2) {
            addCriterion("fmobile_valid_time between", value1, value2, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFmobileValidTimeNotBetween(Date value1, Date value2) {
            addCriterion("fmobile_valid_time not between", value1, value2, "fmobileValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeIsNull() {
            addCriterion("femail_valid_time is null");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeIsNotNull() {
            addCriterion("femail_valid_time is not null");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeEqualTo(Date value) {
            addCriterion("femail_valid_time =", value, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeNotEqualTo(Date value) {
            addCriterion("femail_valid_time <>", value, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeGreaterThan(Date value) {
            addCriterion("femail_valid_time >", value, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("femail_valid_time >=", value, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeLessThan(Date value) {
            addCriterion("femail_valid_time <", value, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeLessThanOrEqualTo(Date value) {
            addCriterion("femail_valid_time <=", value, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeIn(List<Date> values) {
            addCriterion("femail_valid_time in", values, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeNotIn(List<Date> values) {
            addCriterion("femail_valid_time not in", values, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeBetween(Date value1, Date value2) {
            addCriterion("femail_valid_time between", value1, value2, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFemailValidTimeNotBetween(Date value1, Date value2) {
            addCriterion("femail_valid_time not between", value1, value2, "femailValidTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeIsNull() {
            addCriterion("flastlogin_time is null");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeIsNotNull() {
            addCriterion("flastlogin_time is not null");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeEqualTo(Date value) {
            addCriterion("flastlogin_time =", value, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeNotEqualTo(Date value) {
            addCriterion("flastlogin_time <>", value, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeGreaterThan(Date value) {
            addCriterion("flastlogin_time >", value, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("flastlogin_time >=", value, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeLessThan(Date value) {
            addCriterion("flastlogin_time <", value, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeLessThanOrEqualTo(Date value) {
            addCriterion("flastlogin_time <=", value, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeIn(List<Date> values) {
            addCriterion("flastlogin_time in", values, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeNotIn(List<Date> values) {
            addCriterion("flastlogin_time not in", values, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeBetween(Date value1, Date value2) {
            addCriterion("flastlogin_time between", value1, value2, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFlastloginTimeNotBetween(Date value1, Date value2) {
            addCriterion("flastlogin_time not between", value1, value2, "flastloginTime");
            return (Criteria) this;
        }

        public Criteria andFisLogoutIsNull() {
            addCriterion("fis_logout is null");
            return (Criteria) this;
        }

        public Criteria andFisLogoutIsNotNull() {
            addCriterion("fis_logout is not null");
            return (Criteria) this;
        }

        public Criteria andFisLogoutEqualTo(Boolean value) {
            addCriterion("fis_logout =", value, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutNotEqualTo(Boolean value) {
            addCriterion("fis_logout <>", value, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutGreaterThan(Boolean value) {
            addCriterion("fis_logout >", value, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fis_logout >=", value, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutLessThan(Boolean value) {
            addCriterion("fis_logout <", value, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutLessThanOrEqualTo(Boolean value) {
            addCriterion("fis_logout <=", value, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutIn(List<Boolean> values) {
            addCriterion("fis_logout in", values, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutNotIn(List<Boolean> values) {
            addCriterion("fis_logout not in", values, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutBetween(Boolean value1, Boolean value2) {
            addCriterion("fis_logout between", value1, value2, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFisLogoutNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fis_logout not between", value1, value2, "fisLogout");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIsNull() {
            addCriterion("fcreate_time is null");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIsNotNull() {
            addCriterion("fcreate_time is not null");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeEqualTo(Date value) {
            addCriterion("fcreate_time =", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotEqualTo(Date value) {
            addCriterion("fcreate_time <>", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeGreaterThan(Date value) {
            addCriterion("fcreate_time >", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fcreate_time >=", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeLessThan(Date value) {
            addCriterion("fcreate_time <", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("fcreate_time <=", value, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeIn(List<Date> values) {
            addCriterion("fcreate_time in", values, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotIn(List<Date> values) {
            addCriterion("fcreate_time not in", values, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeBetween(Date value1, Date value2) {
            addCriterion("fcreate_time between", value1, value2, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFcreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("fcreate_time not between", value1, value2, "fcreateTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIsNull() {
            addCriterion("fmodify_time is null");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIsNotNull() {
            addCriterion("fmodify_time is not null");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeEqualTo(Date value) {
            addCriterion("fmodify_time =", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotEqualTo(Date value) {
            addCriterion("fmodify_time <>", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeGreaterThan(Date value) {
            addCriterion("fmodify_time >", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fmodify_time >=", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeLessThan(Date value) {
            addCriterion("fmodify_time <", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("fmodify_time <=", value, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeIn(List<Date> values) {
            addCriterion("fmodify_time in", values, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotIn(List<Date> values) {
            addCriterion("fmodify_time not in", values, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeBetween(Date value1, Date value2) {
            addCriterion("fmodify_time between", value1, value2, "fmodifyTime");
            return (Criteria) this;
        }

        public Criteria andFmodifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("fmodify_time not between", value1, value2, "fmodifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_user
     *
     *   do_not_delete_during_merge Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bbc_user
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}