package org.you.oops.order.domain.userorder.repository.po;

import java.util.Date;

public class BbcUserPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fuid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.funame
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String funame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fnickname
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fnickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fheadpic
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fheadpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fuser_level_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fuserLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.foperate_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Boolean foperateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fmarket_bd_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Long fmarketBdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fpasswd
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fpasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fsex
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Boolean fsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fbirthday
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Date fbirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.ftelephone
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String ftelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fmobile
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fmobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fmoblie_is_valid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Boolean fmoblieIsValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fmail
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fmail_is_valid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Boolean fmailIsValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fqq_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fqqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fwechat_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fwechatNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fwangwang_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fwangwangNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fwithdraw_passwd
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fwithdrawPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.ffreeze_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Boolean ffreezeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fverify_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Boolean fverifyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fuser_valid_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private Date fuserValidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.finviter
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String finviter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fregister_from
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    private String fregisterFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fchannel_type
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Boolean fchannelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fis_delete
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Boolean fisDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fremark
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private String fremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fidcard_no
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private String fidcardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fidcard_name
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private String fidcardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fmobile_valid_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Date fmobileValidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.femail_valid_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Date femailValidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.flastlogin_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Date flastloginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fis_logout
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Boolean fisLogout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fcreate_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Date fcreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bbc_user.fmodify_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    private Date fmodifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fuid
     *
     * @return the value of t_bbc_user.fuid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFuid() {
        return fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fuid
     *
     * @param fuid the value for t_bbc_user.fuid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFuid(Long fuid) {
        this.fuid = fuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.funame
     *
     * @return the value of t_bbc_user.funame
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFuname() {
        return funame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.funame
     *
     * @param funame the value for t_bbc_user.funame
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFuname(String funame) {
        this.funame = funame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fnickname
     *
     * @return the value of t_bbc_user.fnickname
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFnickname() {
        return fnickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fnickname
     *
     * @param fnickname the value for t_bbc_user.fnickname
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFnickname(String fnickname) {
        this.fnickname = fnickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fheadpic
     *
     * @return the value of t_bbc_user.fheadpic
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFheadpic() {
        return fheadpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fheadpic
     *
     * @param fheadpic the value for t_bbc_user.fheadpic
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFheadpic(String fheadpic) {
        this.fheadpic = fheadpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fuser_level_id
     *
     * @return the value of t_bbc_user.fuser_level_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFuserLevelId() {
        return fuserLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fuser_level_id
     *
     * @param fuserLevelId the value for t_bbc_user.fuser_level_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFuserLevelId(Long fuserLevelId) {
        this.fuserLevelId = fuserLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.foperate_type
     *
     * @return the value of t_bbc_user.foperate_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Boolean getFoperateType() {
        return foperateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.foperate_type
     *
     * @param foperateType the value for t_bbc_user.foperate_type
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFoperateType(Boolean foperateType) {
        this.foperateType = foperateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fmarket_bd_id
     *
     * @return the value of t_bbc_user.fmarket_bd_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Long getFmarketBdId() {
        return fmarketBdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fmarket_bd_id
     *
     * @param fmarketBdId the value for t_bbc_user.fmarket_bd_id
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFmarketBdId(Long fmarketBdId) {
        this.fmarketBdId = fmarketBdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fpasswd
     *
     * @return the value of t_bbc_user.fpasswd
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFpasswd() {
        return fpasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fpasswd
     *
     * @param fpasswd the value for t_bbc_user.fpasswd
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFpasswd(String fpasswd) {
        this.fpasswd = fpasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fsex
     *
     * @return the value of t_bbc_user.fsex
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Boolean getFsex() {
        return fsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fsex
     *
     * @param fsex the value for t_bbc_user.fsex
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFsex(Boolean fsex) {
        this.fsex = fsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fbirthday
     *
     * @return the value of t_bbc_user.fbirthday
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Date getFbirthday() {
        return fbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fbirthday
     *
     * @param fbirthday the value for t_bbc_user.fbirthday
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFbirthday(Date fbirthday) {
        this.fbirthday = fbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.ftelephone
     *
     * @return the value of t_bbc_user.ftelephone
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFtelephone() {
        return ftelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.ftelephone
     *
     * @param ftelephone the value for t_bbc_user.ftelephone
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFtelephone(String ftelephone) {
        this.ftelephone = ftelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fmobile
     *
     * @return the value of t_bbc_user.fmobile
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFmobile() {
        return fmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fmobile
     *
     * @param fmobile the value for t_bbc_user.fmobile
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFmobile(String fmobile) {
        this.fmobile = fmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fmoblie_is_valid
     *
     * @return the value of t_bbc_user.fmoblie_is_valid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Boolean getFmoblieIsValid() {
        return fmoblieIsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fmoblie_is_valid
     *
     * @param fmoblieIsValid the value for t_bbc_user.fmoblie_is_valid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFmoblieIsValid(Boolean fmoblieIsValid) {
        this.fmoblieIsValid = fmoblieIsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fmail
     *
     * @return the value of t_bbc_user.fmail
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFmail() {
        return fmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fmail
     *
     * @param fmail the value for t_bbc_user.fmail
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFmail(String fmail) {
        this.fmail = fmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fmail_is_valid
     *
     * @return the value of t_bbc_user.fmail_is_valid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Boolean getFmailIsValid() {
        return fmailIsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fmail_is_valid
     *
     * @param fmailIsValid the value for t_bbc_user.fmail_is_valid
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFmailIsValid(Boolean fmailIsValid) {
        this.fmailIsValid = fmailIsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fqq_no
     *
     * @return the value of t_bbc_user.fqq_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFqqNo() {
        return fqqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fqq_no
     *
     * @param fqqNo the value for t_bbc_user.fqq_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFqqNo(String fqqNo) {
        this.fqqNo = fqqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fwechat_no
     *
     * @return the value of t_bbc_user.fwechat_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFwechatNo() {
        return fwechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fwechat_no
     *
     * @param fwechatNo the value for t_bbc_user.fwechat_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFwechatNo(String fwechatNo) {
        this.fwechatNo = fwechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fwangwang_no
     *
     * @return the value of t_bbc_user.fwangwang_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFwangwangNo() {
        return fwangwangNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fwangwang_no
     *
     * @param fwangwangNo the value for t_bbc_user.fwangwang_no
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFwangwangNo(String fwangwangNo) {
        this.fwangwangNo = fwangwangNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fwithdraw_passwd
     *
     * @return the value of t_bbc_user.fwithdraw_passwd
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFwithdrawPasswd() {
        return fwithdrawPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fwithdraw_passwd
     *
     * @param fwithdrawPasswd the value for t_bbc_user.fwithdraw_passwd
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFwithdrawPasswd(String fwithdrawPasswd) {
        this.fwithdrawPasswd = fwithdrawPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.ffreeze_status
     *
     * @return the value of t_bbc_user.ffreeze_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Boolean getFfreezeStatus() {
        return ffreezeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.ffreeze_status
     *
     * @param ffreezeStatus the value for t_bbc_user.ffreeze_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFfreezeStatus(Boolean ffreezeStatus) {
        this.ffreezeStatus = ffreezeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fverify_status
     *
     * @return the value of t_bbc_user.fverify_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Boolean getFverifyStatus() {
        return fverifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fverify_status
     *
     * @param fverifyStatus the value for t_bbc_user.fverify_status
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFverifyStatus(Boolean fverifyStatus) {
        this.fverifyStatus = fverifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fuser_valid_time
     *
     * @return the value of t_bbc_user.fuser_valid_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public Date getFuserValidTime() {
        return fuserValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fuser_valid_time
     *
     * @param fuserValidTime the value for t_bbc_user.fuser_valid_time
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFuserValidTime(Date fuserValidTime) {
        this.fuserValidTime = fuserValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.finviter
     *
     * @return the value of t_bbc_user.finviter
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFinviter() {
        return finviter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.finviter
     *
     * @param finviter the value for t_bbc_user.finviter
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFinviter(String finviter) {
        this.finviter = finviter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fregister_from
     *
     * @return the value of t_bbc_user.fregister_from
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public String getFregisterFrom() {
        return fregisterFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fregister_from
     *
     * @param fregisterFrom the value for t_bbc_user.fregister_from
     *
     *   Tue Jan 26 17:05:50 GMT+08:00 2021
     */
    public void setFregisterFrom(String fregisterFrom) {
        this.fregisterFrom = fregisterFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fchannel_type
     *
     * @return the value of t_bbc_user.fchannel_type
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Boolean getFchannelType() {
        return fchannelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fchannel_type
     *
     * @param fchannelType the value for t_bbc_user.fchannel_type
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFchannelType(Boolean fchannelType) {
        this.fchannelType = fchannelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fis_delete
     *
     * @return the value of t_bbc_user.fis_delete
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Boolean getFisDelete() {
        return fisDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fis_delete
     *
     * @param fisDelete the value for t_bbc_user.fis_delete
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFisDelete(Boolean fisDelete) {
        this.fisDelete = fisDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fremark
     *
     * @return the value of t_bbc_user.fremark
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public String getFremark() {
        return fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fremark
     *
     * @param fremark the value for t_bbc_user.fremark
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFremark(String fremark) {
        this.fremark = fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fidcard_no
     *
     * @return the value of t_bbc_user.fidcard_no
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public String getFidcardNo() {
        return fidcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fidcard_no
     *
     * @param fidcardNo the value for t_bbc_user.fidcard_no
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFidcardNo(String fidcardNo) {
        this.fidcardNo = fidcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fidcard_name
     *
     * @return the value of t_bbc_user.fidcard_name
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public String getFidcardName() {
        return fidcardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fidcard_name
     *
     * @param fidcardName the value for t_bbc_user.fidcard_name
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFidcardName(String fidcardName) {
        this.fidcardName = fidcardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fmobile_valid_time
     *
     * @return the value of t_bbc_user.fmobile_valid_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Date getFmobileValidTime() {
        return fmobileValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fmobile_valid_time
     *
     * @param fmobileValidTime the value for t_bbc_user.fmobile_valid_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFmobileValidTime(Date fmobileValidTime) {
        this.fmobileValidTime = fmobileValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.femail_valid_time
     *
     * @return the value of t_bbc_user.femail_valid_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Date getFemailValidTime() {
        return femailValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.femail_valid_time
     *
     * @param femailValidTime the value for t_bbc_user.femail_valid_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFemailValidTime(Date femailValidTime) {
        this.femailValidTime = femailValidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.flastlogin_time
     *
     * @return the value of t_bbc_user.flastlogin_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Date getFlastloginTime() {
        return flastloginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.flastlogin_time
     *
     * @param flastloginTime the value for t_bbc_user.flastlogin_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFlastloginTime(Date flastloginTime) {
        this.flastloginTime = flastloginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fis_logout
     *
     * @return the value of t_bbc_user.fis_logout
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Boolean getFisLogout() {
        return fisLogout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fis_logout
     *
     * @param fisLogout the value for t_bbc_user.fis_logout
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFisLogout(Boolean fisLogout) {
        this.fisLogout = fisLogout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fcreate_time
     *
     * @return the value of t_bbc_user.fcreate_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Date getFcreateTime() {
        return fcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fcreate_time
     *
     * @param fcreateTime the value for t_bbc_user.fcreate_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFcreateTime(Date fcreateTime) {
        this.fcreateTime = fcreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bbc_user.fmodify_time
     *
     * @return the value of t_bbc_user.fmodify_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public Date getFmodifyTime() {
        return fmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bbc_user.fmodify_time
     *
     * @param fmodifyTime the value for t_bbc_user.fmodify_time
     *
     *   Tue Jan 26 17:05:51 GMT+08:00 2021
     */
    public void setFmodifyTime(Date fmodifyTime) {
        this.fmodifyTime = fmodifyTime;
    }
}